export declare enum AchievementType {
    FIRST_ALGORITHM = "FIRST_ALGORITHM",
    STREAK_7 = "STREAK_7",
    STREAK_30 = "STREAK_30",
    QUESTIONS_100 = "QUESTIONS_100",
    ALL_SORTING = "ALL_SORTING",
    GRAPH_MASTER = "GRAPH_MASTER",
    DP_MASTER = "DP_MASTER",
    TREE_EXPERT = "TREE_EXPERT"
}
