import { InterviewQuestion } from '../interviewMetadata';

export const ADVANCED_STRINGS_INTERVIEW_QUESTIONS: InterviewQuestion[] = [
  {
    id: 'adv-str-1',
    title: 'Shortest Palindrome',
    category: 'advanced-strings',
    pattern: 'KMP Algorithm',
    subPattern: 'KMP Prefix Function',
    difficulty: 'hard',
    description: 'You are given a string s. You can convert it to a palindrome by adding characters in front of it. Find and return the shortest palindrome you can find by performing this transformation.',
    frequency: 'top',
    starRating: 5,
    expectedTime: 'O(N)',
    expectedSpace: 'O(N)',
    estimatedTime: '30 mins',
    platform: 'LeetCode',
    platformLink: 'https://leetcode.com/problems/shortest-palindrome/',
    status: 'Not Started',
    notes: '',
    bookmarked: false,
    completed: false,
    tags: ['String', 'KMP', 'Rolling Hash', 'String Matching'],
    topic: 'Advanced Strings',
    companies: ['Google', 'Amazon', 'Microsoft', 'Pocket Gems'],
    leetcodeNumber: 214,
    leetcodeLink: 'https://leetcode.com/problems/shortest-palindrome/',
    visualizerSlug: 'string',
    hints: ['Construct string temp = s + "#" + reverse(s) and compute KMP Partial Match Table (LPS).'],
    bruteForce: 'Check all prefix lengths to see if prefix of s is palindrome.',
    optimalApproach: 'Use KMP prefix function on s + "#" + rev(s) to find longest palindromic prefix in O(N).',
    commonMistakes: ['Forgetting delimiter between original and reversed string.'],
    prerequisites: ['KMP Algorithm', 'LPS Array'],
    relatedQuestions: ['adv-str-2', 'adv-str-4'],
    acceptanceRate: '32.6%',
  },
  {
    id: 'adv-str-2',
    title: 'Find the Index of the First Occurrence in a String',
    category: 'advanced-strings',
    pattern: 'KMP Algorithm',
    subPattern: 'String Search (strStr)',
    difficulty: 'easy',
    description: 'Given two strings needle and haystack, return the index of the first occurrence of needle in haystack, or -1 if needle is not part of haystack.',
    frequency: 'top',
    starRating: 5,
    expectedTime: 'O(N + M)',
    expectedSpace: 'O(M)',
    estimatedTime: '20 mins',
    platform: 'LeetCode',
    platformLink: 'https://leetcode.com/problems/find-the-index-of-the-first-occurrence-in-a-string/',
    status: 'Not Started',
    notes: '',
    bookmarked: false,
    completed: false,
    tags: ['Two Pointers', 'String', 'String Matching'],
    topic: 'Advanced Strings',
    companies: ['Amazon', 'Microsoft', 'Google', 'Apple', 'Meta'],
    leetcodeNumber: 28,
    leetcodeLink: 'https://leetcode.com/problems/find-the-index-of-the-first-occurrence-in-a-string/',
    visualizerSlug: 'string',
    hints: ['Precompute LPS table of needle to avoid quadratic fallback on mismatches.'],
    bruteForce: 'Check needle starting at each index in haystack (O(N * M)).',
    optimalApproach: 'Knuth-Morris-Pratt (KMP) linear string matching algorithm.',
    commonMistakes: ['Incorrect index update when mismatch occurs after partial matches.'],
    prerequisites: ['KMP Algorithm', 'Prefix Function'],
    relatedQuestions: ['adv-str-1', 'adv-str-7'],
    acceptanceRate: '40.8%',
  },
  {
    id: 'adv-str-3',
    title: 'Repeated Substring Pattern',
    category: 'advanced-strings',
    pattern: 'KMP Algorithm',
    subPattern: 'String Periodicity',
    difficulty: 'easy',
    description: 'Given a string s, check if it can be constructed by taking a substring of it and appending multiple copies of the substring together.',
    frequency: 'high',
    starRating: 4,
    expectedTime: 'O(N)',
    expectedSpace: 'O(N)',
    estimatedTime: '15 mins',
    platform: 'LeetCode',
    platformLink: 'https://leetcode.com/problems/repeated-substring-pattern/',
    status: 'Not Started',
    notes: '',
    bookmarked: false,
    completed: false,
    tags: ['String', 'String Matching', 'KMP'],
    topic: 'Advanced Strings',
    companies: ['Amazon', 'Google'],
    leetcodeNumber: 459,
    leetcodeLink: 'https://leetcode.com/problems/repeated-substring-pattern/',
    visualizerSlug: 'string',
    hints: ['If s is periodic, s must be a substring of (s + s)[1 : 2*N - 1], or use LPS array length check.'],
    bruteForce: 'Try all possible pattern lengths that divide s.length.',
    optimalApproach: 'Check if len - lps[len - 1] divides len and lps[len - 1] > 0 using KMP.',
    commonMistakes: ['Not checking if LPS length is greater than 0.'],
    prerequisites: ['KMP Algorithm'],
    relatedQuestions: ['adv-str-2', 'adv-str-1'],
    acceptanceRate: '45.7%',
  },
  {
    id: 'adv-str-4',
    title: 'Longest Happy Prefix',
    category: 'advanced-strings',
    pattern: 'KMP Algorithm',
    subPattern: 'Longest Prefix Suffix',
    difficulty: 'hard',
    description: 'A string is called a happy prefix if is a non-empty prefix which is also a suffix (excluding the string itself). Find the longest happy prefix of s.',
    frequency: 'high',
    starRating: 5,
    expectedTime: 'O(N)',
    expectedSpace: 'O(N)',
    estimatedTime: '25 mins',
    platform: 'LeetCode',
    platformLink: 'https://leetcode.com/problems/longest-happy-prefix/',
    status: 'Not Started',
    notes: '',
    bookmarked: false,
    completed: false,
    tags: ['String', 'KMP', 'Rolling Hash', 'String Matching'],
    topic: 'Advanced Strings',
    companies: ['Google'],
    leetcodeNumber: 1392,
    leetcodeLink: 'https://leetcode.com/problems/longest-happy-prefix/',
    visualizerSlug: 'string',
    hints: ['The last element of the KMP LPS array gives the exact length of the longest happy prefix.'],
    bruteForce: 'Compare all prefixes and suffixes.',
    optimalApproach: 'Compute KMP LPS array in O(N) time and slice s[0...LPS[n-1]].',
    commonMistakes: ['Off-by-one errors when slicing string using LPS length.'],
    prerequisites: ['KMP Algorithm', 'LPS Array'],
    relatedQuestions: ['adv-str-1', 'adv-str-2'],
    acceptanceRate: '45.1%',
  },
  {
    id: 'adv-str-5',
    title: 'Sum of Scores of Built Strings',
    category: 'advanced-strings',
    pattern: 'Z-Algorithm',
    subPattern: 'Z-Array Construction',
    difficulty: 'hard',
    description: 'Calculate the total sum of scores of strings built at each step, where score is length of longest common prefix between s and current built suffix.',
    frequency: 'high',
    starRating: 5,
    expectedTime: 'O(N)',
    expectedSpace: 'O(N)',
    estimatedTime: '35 mins',
    platform: 'LeetCode',
    platformLink: 'https://leetcode.com/problems/sum-of-scores-of-built-strings/',
    status: 'Not Started',
    notes: '',
    bookmarked: false,
    completed: false,
    tags: ['String', 'Z-Algorithm', 'String Matching', 'Prefix Function'],
    topic: 'Advanced Strings',
    companies: ['Google', 'Uber'],
    leetcodeNumber: 2223,
    leetcodeLink: 'https://leetcode.com/problems/sum-of-scores-of-built-strings/',
    visualizerSlug: 'string',
    hints: ['The Z-box algorithm computes LCP of s and every suffix of s in O(N) total time.'],
    bruteForce: 'Compute LCP for each suffix using naive comparison O(N^2).',
    optimalApproach: 'Compute Z-array for string s and sum all values in Z-array + s.length.',
    commonMistakes: ['Forgetting to add s.length for full string self-match.'],
    prerequisites: ['Z-Algorithm'],
    relatedQuestions: ['adv-str-6', 'adv-str-4'],
    acceptanceRate: '38.9%',
  },
  {
    id: 'adv-str-6',
    title: 'Z-Algorithm Pattern Matching',
    category: 'advanced-strings',
    pattern: 'Z-Algorithm',
    subPattern: 'Concatenated Z-Box',
    difficulty: 'medium',
    description: 'Find all occurrences of a pattern P in text T using the Z-algorithm by constructing string P + "$" + T.',
    frequency: 'medium',
    starRating: 4,
    expectedTime: 'O(N + M)',
    expectedSpace: 'O(N + M)',
    estimatedTime: '25 mins',
    platform: 'LeetCode',
    platformLink: 'https://leetcode.com/problems/z-algorithm-pattern-matching/',
    status: 'Not Started',
    notes: '',
    bookmarked: false,
    completed: false,
    tags: ['String', 'Z-Algorithm', 'String Matching'],
    topic: 'Advanced Strings',
    companies: ['Google', 'Meta'],
    visualizerSlug: 'string',
    hints: ['Construct S = P + "$" + T. Calculate Z-array for S. Match whenever Z[i] == P.length.'],
    bruteForce: 'Naive pattern matching with inner loop O(N * M).',
    optimalApproach: 'Linear Z-algorithm matching in O(N + M) time.',
    commonMistakes: ['Choosing a delimiter character that can appear inside P or T.'],
    prerequisites: ['Z-Algorithm'],
    relatedQuestions: ['adv-str-5', 'adv-str-2'],
    acceptanceRate: '58.2%',
  },
  {
    id: 'adv-str-7',
    title: 'Rabin Karp String Search',
    category: 'advanced-strings',
    pattern: 'Rabin-Karp & Rolling Hash',
    subPattern: 'Rolling Hash Search',
    difficulty: 'medium',
    description: 'Implement string matching using Rabin-Karp polynomial rolling hash technique to match patterns efficiently.',
    frequency: 'top',
    starRating: 5,
    expectedTime: 'O(N + M)',
    expectedSpace: 'O(1)',
    estimatedTime: '25 mins',
    platform: 'LeetCode',
    platformLink: 'https://leetcode.com/problems/rabin-karp-string-search/',
    status: 'Not Started',
    notes: '',
    bookmarked: false,
    completed: false,
    tags: ['String', 'Rolling Hash', 'Hash Table'],
    topic: 'Advanced Strings',
    companies: ['Amazon', 'Google', 'Microsoft'],
    visualizerSlug: 'string',
    hints: ['Use hash(s[i+1...i+m]) = (hash(s[i...i+m-1]) - s[i]*p^(m-1))*p + s[i+m] mod Q.'],
    bruteForce: 'Recompute full string hash at every window sliding step O(N * M).',
    optimalApproach: 'Rolling hash with constant time O(1) window shift updates.',
    commonMistakes: ['Failing to handle negative results from modular subtraction.'],
    prerequisites: ['Rolling Hash', 'Modular Arithmetic'],
    relatedQuestions: ['adv-str-8', 'adv-str-9'],
    acceptanceRate: '54.7%',
  },
  {
    id: 'adv-str-8',
    title: 'Distinct Echo Substrings',
    category: 'advanced-strings',
    pattern: 'Rabin-Karp & Rolling Hash',
    subPattern: 'Polynomial Hash Substrings',
    difficulty: 'hard',
    description: 'Return the number of distinct non-empty substrings of text that can be written as the concatenation of some string with itself.',
    frequency: 'high',
    starRating: 4,
    expectedTime: 'O(N^2)',
    expectedSpace: 'O(N)',
    estimatedTime: '35 mins',
    platform: 'LeetCode',
    platformLink: 'https://leetcode.com/problems/distinct-echo-substrings/',
    status: 'Not Started',
    notes: '',
    bookmarked: false,
    completed: false,
    tags: ['String', 'Trie', 'Rolling Hash', 'Hash Function'],
    topic: 'Advanced Strings',
    companies: ['Google'],
    leetcodeNumber: 1316,
    leetcodeLink: 'https://leetcode.com/problems/distinct-echo-substrings/',
    visualizerSlug: 'string',
    hints: ['Compute prefix rolling hashes for fast O(1) substring hash comparisons text[i...i+k] vs text[i+k...i+2k].'],
    bruteForce: 'Compare all substring pairs using direct character checking O(N^3).',
    optimalApproach: 'Prefix Polynomial Rolling Hash with set deduplication in O(N^2).',
    commonMistakes: ['Hash collisions without double hashing or explicit fallback check.'],
    prerequisites: ['Rolling Hash'],
    relatedQuestions: ['adv-str-7', 'adv-str-9'],
    acceptanceRate: '49.2%',
  },
  {
    id: 'adv-str-9',
    title: 'Longest Duplicate Substring',
    category: 'advanced-strings',
    pattern: 'Rabin-Karp & Rolling Hash',
    subPattern: 'Binary Search + Rolling Hash',
    difficulty: 'hard',
    description: 'Given a string s, consider all duplicated substrings: possible substrings that occur 2 or more times. Return a duplicated substring that has the longest possible length.',
    frequency: 'top',
    starRating: 5,
    expectedTime: 'O(N log N)',
    expectedSpace: 'O(N)',
    estimatedTime: '45 mins',
    platform: 'LeetCode',
    platformLink: 'https://leetcode.com/problems/longest-duplicate-substring/',
    status: 'Not Started',
    notes: '',
    bookmarked: false,
    completed: false,
    tags: ['String', 'Binary Search', 'Rolling Hash', 'Suffix Array'],
    topic: 'Advanced Strings',
    companies: ['Google', 'Amazon', 'Microsoft'],
    leetcodeNumber: 1044,
    leetcodeLink: 'https://leetcode.com/problems/longest-duplicate-substring/',
    visualizerSlug: 'string',
    hints: ['Binary search on duplicate substring length L. Use Rabin-Karp rolling hash with double modulo to verify length L.'],
    bruteForce: 'Check all substring lengths and pairs O(N^3).',
    optimalApproach: 'Binary Search on answer L (1 to N) + Rabin-Karp rolling hash in O(N log N).',
    commonMistakes: ['Single hash collisions causing false positives.'],
    prerequisites: ['Binary Search', 'Rabin-Karp Rolling Hash'],
    relatedQuestions: ['adv-str-7', 'adv-str-12'],
    acceptanceRate: '30.8%',
  },
  {
    id: 'adv-str-10',
    title: 'Longest Palindromic Substring using Manacher',
    category: 'advanced-strings',
    pattern: 'Pattern & Wildcard Matching',
    subPattern: "Manacher's Algorithm",
    difficulty: 'medium',
    description: "Given a string s, return the longest palindromic substring in s using Manacher's Algorithm in linear time.",
    frequency: 'top',
    starRating: 5,
    expectedTime: 'O(N)',
    expectedSpace: 'O(N)',
    estimatedTime: '30 mins',
    platform: 'LeetCode',
    platformLink: 'https://leetcode.com/problems/longest-palindromic-substring/',
    status: 'Not Started',
    notes: '',
    bookmarked: false,
    completed: false,
    tags: ['String', 'Dynamic Programming', 'Manacher'],
    topic: 'Advanced Strings',
    companies: ['Amazon', 'Microsoft', 'Google', 'Apple', 'Meta'],
    leetcodeNumber: 5,
    leetcodeLink: 'https://leetcode.com/problems/longest-palindromic-substring/',
    visualizerSlug: 'string',
    hints: ['Transform s by inserting "#" between chars. Maintain center C and right boundary R of palindrome.'],
    bruteForce: 'Expand around center for each index in O(N^2).',
    optimalApproach: "Manacher's Algorithm exploiting symmetry to skip redundant expansions in O(N).",
    commonMistakes: ['Incorrect radius reflection math i_mirror = 2*C - i.'],
    prerequisites: ['Palindromes', 'Two Pointers'],
    relatedQuestions: ['adv-str-11', 'adv-str-1'],
    acceptanceRate: '33.7%',
  },
  {
    id: 'adv-str-11',
    title: 'Count Palindromic Substrings via Manacher',
    category: 'advanced-strings',
    pattern: 'Pattern & Wildcard Matching',
    subPattern: "Manacher's Radius Count",
    difficulty: 'medium',
    description: 'Count total number of palindromic substrings in a given string s using linear Manacher radius calculation.',
    frequency: 'high',
    starRating: 4,
    expectedTime: 'O(N)',
    expectedSpace: 'O(N)',
    estimatedTime: '20 mins',
    platform: 'LeetCode',
    platformLink: 'https://leetcode.com/problems/palindromic-substrings/',
    status: 'Not Started',
    notes: '',
    bookmarked: false,
    completed: false,
    tags: ['String', 'Dynamic Programming', 'Manacher'],
    topic: 'Advanced Strings',
    companies: ['Amazon', 'Google', 'Meta'],
    leetcodeNumber: 647,
    leetcodeLink: 'https://leetcode.com/problems/palindromic-substrings/',
    visualizerSlug: 'string',
    hints: ['Each radius P[i] in modified string transformed with "#" contributes (P[i] + 1) / 2 palindromes.'],
    bruteForce: 'Expand around center at each index summing counts O(N^2).',
    optimalApproach: "Manacher's linear scan, summing floor((P[i]+1)/2).",
    commonMistakes: ['Double counting due to delimiter characters.'],
    prerequisites: ["Manacher's Algorithm"],
    relatedQuestions: ['adv-str-10', 'adv-str-1'],
    acceptanceRate: '69.1%',
  },
  {
    id: 'adv-str-12',
    title: 'Construct Suffix Array and LCP Array',
    category: 'advanced-strings',
    pattern: 'Suffix Structures & Automata',
    subPattern: 'Suffix Array Ranking',
    difficulty: 'hard',
    description: 'Construct the Suffix Array and Longest Common Prefix (LCP) Array (Kasai algorithm) for a string of length N.',
    frequency: 'high',
    starRating: 5,
    expectedTime: 'O(N log N)',
    expectedSpace: 'O(N)',
    estimatedTime: '45 mins',
    platform: 'LeetCode',
    platformLink: 'https://leetcode.com/problems/suffix-array-lcp/',
    status: 'Not Started',
    notes: '',
    bookmarked: false,
    completed: false,
    tags: ['String', 'Suffix Array', 'Kasai Algorithm'],
    topic: 'Advanced Strings',
    companies: ['Google', 'Meta'],
    visualizerSlug: 'string',
    hints: ['Use prefix doubling (Manber-Myers) to build Suffix Array in O(N log N). Use Kasai algorithm for LCP array in O(N).'],
    bruteForce: 'Sort suffixes directly with comparison O(N^2 log N).',
    optimalApproach: 'Prefix doubling SA construction + Kasai algorithm for LCP.',
    commonMistakes: ['Off-by-one errors when computing rank inverse mapping.'],
    prerequisites: ['Suffix Array', 'Sorting'],
    relatedQuestions: ['adv-str-13', 'adv-str-9'],
    acceptanceRate: '42.1%',
  },
  {
    id: 'adv-str-13',
    title: 'Longest Common Substring of Two Strings',
    category: 'advanced-strings',
    pattern: 'Suffix Structures & Automata',
    subPattern: 'Suffix Array Concatenation',
    difficulty: 'hard',
    description: 'Find the longest common substring shared between two strings s1 and s2 using Suffix Array and LCP array.',
    frequency: 'high',
    starRating: 5,
    expectedTime: 'O((N + M) log(N + M))',
    expectedSpace: 'O(N + M)',
    estimatedTime: '40 mins',
    platform: 'LeetCode',
    platformLink: 'https://leetcode.com/problems/longest-common-substring/',
    status: 'Not Started',
    notes: '',
    bookmarked: false,
    completed: false,
    tags: ['String', 'Suffix Array', 'LCP Array', 'Dynamic Programming'],
    topic: 'Advanced Strings',
    companies: ['Amazon', 'Google', 'Microsoft'],
    visualizerSlug: 'string',
    hints: ['Concatenate s1 + "#" + s2 + "$". Build Suffix Array and LCP array. Maximum LCP between adjacent suffixes belonging to different original strings is the answer.'],
    bruteForce: 'Dynamic programming matrix O(N * M) or naive substring check.',
    optimalApproach: 'Combined Suffix Array + LCP adjacent owner check in O((N+M) log(N+M)).',
    commonMistakes: ['Ignoring suffix owner verification (both suffixes coming from same string).'],
    prerequisites: ['Suffix Array', 'LCP Array'],
    relatedQuestions: ['adv-str-12', 'adv-str-9'],
    acceptanceRate: '47.5%',
  },
  {
    id: 'adv-str-14',
    title: 'Suffix Automaton Basic Search',
    category: 'advanced-strings',
    pattern: 'Suffix Structures & Automata',
    subPattern: 'Directed Acyclic Word Graph (DAWG)',
    difficulty: 'hard',
    description: 'Construct a Suffix Automaton (SAM) for a string and check substring queries in O(length) time per query.',
    frequency: 'medium',
    starRating: 5,
    expectedTime: 'O(N)',
    expectedSpace: 'O(N)',
    estimatedTime: '50 mins',
    platform: 'LeetCode',
    platformLink: 'https://leetcode.com/problems/suffix-automaton-search/',
    status: 'Not Started',
    notes: '',
    bookmarked: false,
    completed: false,
    tags: ['String', 'Suffix Automaton', 'Graph', 'DAWG'],
    topic: 'Advanced Strings',
    companies: ['Google'],
    visualizerSlug: 'string',
    hints: ['Build Suffix Automaton incrementally character by character maintaining endpos equivalence classes.'],
    bruteForce: 'Search with Trie of all suffixes (O(N^2) space).',
    optimalApproach: 'Suffix Automaton construction in O(N) time and linear O(N) state space.',
    commonMistakes: ['Incorrect suffix link updates when cloning state transition nodes.'],
    prerequisites: ['Suffix Automaton', 'Graph Theory'],
    relatedQuestions: ['adv-str-15', 'adv-str-12'],
    acceptanceRate: '34.2%',
  },
  {
    id: 'adv-str-15',
    title: 'Distinct Substrings Count with Suffix Tree',
    category: 'advanced-strings',
    pattern: 'Suffix Structures & Automata',
    subPattern: 'Ukkonen Suffix Tree',
    difficulty: 'hard',
    description: 'Count the total number of distinct non-empty substrings in a string using Suffix Tree or Suffix Automaton state sum.',
    frequency: 'medium',
    starRating: 5,
    expectedTime: 'O(N)',
    expectedSpace: 'O(N)',
    estimatedTime: '45 mins',
    platform: 'LeetCode',
    platformLink: 'https://leetcode.com/problems/distinct-substrings-count/',
    status: 'Not Started',
    notes: '',
    bookmarked: false,
    completed: false,
    tags: ['String', 'Suffix Tree', 'Suffix Automaton'],
    topic: 'Advanced Strings',
    companies: ['Google', 'Uber'],
    visualizerSlug: 'string',
    hints: ['In Suffix Automaton, sum(len[i] - len[link[i]]) over all states gives total distinct substrings.'],
    bruteForce: 'Insert all substrings into a HashSet O(N^2).',
    optimalApproach: 'State length difference summation over Suffix Automaton states in O(N).',
    commonMistakes: ['Double counting root node length.'],
    prerequisites: ['Suffix Automaton', 'Suffix Tree'],
    relatedQuestions: ['adv-str-14', 'adv-str-12'],
    acceptanceRate: '39.8%',
  },
  {
    id: 'adv-str-16',
    title: 'Smallest Lexicographical String After Substring Swaps',
    category: 'advanced-strings',
    pattern: 'Pattern & Wildcard Matching',
    subPattern: 'Lexicographical Greedy Selection',
    difficulty: 'medium',
    description: 'Find the lexicographically smallest string possible by performing at most k character swaps or transformation rules.',
    frequency: 'high',
    starRating: 4,
    expectedTime: 'O(N)',
    expectedSpace: 'O(1)',
    estimatedTime: '20 mins',
    platform: 'LeetCode',
    platformLink: 'https://leetcode.com/problems/smallest-lexicographical-string/',
    status: 'Not Started',
    notes: '',
    bookmarked: false,
    completed: false,
    tags: ['String', 'Greedy', 'Sorting'],
    topic: 'Advanced Strings',
    companies: ['Amazon', 'Google'],
    leetcodeNumber: 1663,
    leetcodeLink: 'https://leetcode.com/problems/smallest-string-with-a-given-numeric-value/',
    visualizerSlug: 'string',
    hints: ['Greedily set earliest characters to "a" while keeping remaining value sum within valid character bounds.'],
    bruteForce: 'Try all valid string combinations.',
    optimalApproach: 'Greedy right-to-left or left-to-right character assignment in O(N).',
    commonMistakes: ['Over-allocating character values past "z" boundary.'],
    prerequisites: ['Greedy', 'String Manipulations'],
    relatedQuestions: ['adv-str-17', 'adv-str-20'],
    acceptanceRate: '66.4%',
  },
  {
    id: 'adv-str-17',
    title: 'Lexicographically Smallest Equivalent String',
    category: 'advanced-strings',
    pattern: 'Pattern & Wildcard Matching',
    subPattern: 'Union Find Character Equivalences',
    difficulty: 'medium',
    description: 'Given equivalent character pairs s1 and s2, replace characters in baseStr with their lexicographically smallest equivalent character.',
    frequency: 'high',
    starRating: 4,
    expectedTime: 'O(N * alpha)',
    expectedSpace: 'O(26)',
    estimatedTime: '20 mins',
    platform: 'LeetCode',
    platformLink: 'https://leetcode.com/problems/lexicographically-smallest-equivalent-string/',
    status: 'Not Started',
    notes: '',
    bookmarked: false,
    completed: false,
    tags: ['String', 'Union Find', 'Disjoint Set'],
    topic: 'Advanced Strings',
    companies: ['Google', 'Amazon'],
    leetcodeNumber: 1061,
    leetcodeLink: 'https://leetcode.com/problems/lexicographically-smallest-equivalent-string/',
    visualizerSlug: 'string',
    hints: ['Use Disjoint Set Union (DSU) on 26 lowercase characters, always making the smaller character the root parent.'],
    bruteForce: 'Graph BFS to find all connected component components per character.',
    optimalApproach: 'Union-Find with min-character parent root selection.',
    commonMistakes: ['Not compressing paths in find operation.'],
    prerequisites: ['DSU', 'Graph'],
    relatedQuestions: ['adv-str-16', 'adv-str-20'],
    acceptanceRate: '76.2%',
  },
  {
    id: 'adv-str-18',
    title: 'Wildcard Matching (Pattern Match)',
    category: 'advanced-strings',
    pattern: 'Pattern & Wildcard Matching',
    subPattern: 'Wildcard DP / Greedy Match',
    difficulty: 'hard',
    description: 'Given an input string s and a pattern p, implement wildcard pattern matching with support for "?" and "*".',
    frequency: 'top',
    starRating: 5,
    expectedTime: 'O(N * M)',
    expectedSpace: 'O(N * M)',
    estimatedTime: '35 mins',
    platform: 'LeetCode',
    platformLink: 'https://leetcode.com/problems/wildcard-matching/',
    status: 'Not Started',
    notes: '',
    bookmarked: false,
    completed: false,
    tags: ['String', 'Dynamic Programming', 'Greedy', 'Recursion'],
    topic: 'Advanced Strings',
    companies: ['Amazon', 'Google', 'Microsoft', 'Meta'],
    leetcodeNumber: 44,
    leetcodeLink: 'https://leetcode.com/problems/wildcard-matching/',
    visualizerSlug: 'string',
    hints: ['"?" matches any single character. "*" matches any sequence of characters including empty.'],
    bruteForce: 'Recursive backtracking without memoization O(2^(N+M)).',
    optimalApproach: '2D Dynamic Programming table or 2-pointer backtracking with asterisk position tracking.',
    commonMistakes: ['Handling multiple consecutive asterisks ("***").'],
    prerequisites: ['Dynamic Programming', 'Two Pointers'],
    relatedQuestions: ['adv-str-19', 'adv-str-2'],
    acceptanceRate: '27.4%',
  },
  {
    id: 'adv-str-19',
    title: 'Regular Expression Matching (Pattern Match)',
    category: 'advanced-strings',
    pattern: 'Pattern & Wildcard Matching',
    subPattern: 'Regex State DP',
    difficulty: 'hard',
    description: 'Given an input string s and a pattern p, implement regular expression matching with support for "." and "*".',
    frequency: 'top',
    starRating: 5,
    expectedTime: 'O(N * M)',
    expectedSpace: 'O(N * M)',
    estimatedTime: '40 mins',
    platform: 'LeetCode',
    platformLink: 'https://leetcode.com/problems/regular-expression-matching/',
    status: 'Not Started',
    notes: '',
    bookmarked: false,
    completed: false,
    tags: ['String', 'Dynamic Programming', 'Recursion'],
    topic: 'Advanced Strings',
    companies: ['Amazon', 'Google', 'Microsoft', 'Apple', 'Meta'],
    leetcodeNumber: 10,
    leetcodeLink: 'https://leetcode.com/problems/regular-expression-matching/',
    visualizerSlug: 'string',
    hints: ['"*" matches zero or more of the PRECEDING element. Handle 0 occurrences vs 1+ occurrences in DP.'],
    bruteForce: 'Brute force recursion expanding regex states.',
    optimalApproach: '2D DP grid dp[i][j] representing s[i...] matching p[j...].',
    commonMistakes: ['Confusing regex wildcard "*" (modifier) with simple wildcard "*".'],
    prerequisites: ['Dynamic Programming', 'Strings'],
    relatedQuestions: ['adv-str-18', 'adv-str-10'],
    acceptanceRate: '28.3%',
  },
  {
    id: 'adv-str-20',
    title: 'String Matching in an Array',
    category: 'advanced-strings',
    pattern: 'Pattern & Wildcard Matching',
    subPattern: 'Basic Substring Inclusion',
    difficulty: 'easy',
    description: 'Given an array of string words, return all strings in words that is a substring of another word in any order.',
    frequency: 'medium',
    starRating: 3,
    expectedTime: 'O(N^2 * L)',
    expectedSpace: 'O(N)',
    estimatedTime: '15 mins',
    platform: 'LeetCode',
    platformLink: 'https://leetcode.com/problems/string-matching-in-an-array/',
    status: 'Not Started',
    notes: '',
    bookmarked: false,
    completed: false,
    tags: ['String', 'String Matching'],
    topic: 'Advanced Strings',
    companies: ['Amazon'],
    leetcodeNumber: 1408,
    leetcodeLink: 'https://leetcode.com/problems/string-matching-in-an-array/',
    visualizerSlug: 'string',
    hints: ['Sort words by length. Check if shorter word is contained in any longer word.'],
    bruteForce: 'Nested loop checking includes() for all pairs.',
    optimalApproach: 'Length sorting + substring check filter.',
    commonMistakes: ['Comparing a string with itself.'],
    prerequisites: ['Strings'],
    relatedQuestions: ['adv-str-21', 'adv-str-3'],
    acceptanceRate: '64.5%',
  },
  {
    id: 'adv-str-21',
    title: 'Camelcase Matching',
    category: 'advanced-strings',
    pattern: 'Pattern & Wildcard Matching',
    subPattern: 'Subsequence Uppercase Match',
    difficulty: 'medium',
    description: 'Given an array of queries and a pattern, return boolean array indicating if query matches pattern under CamelCase rules.',
    frequency: 'medium',
    starRating: 4,
    expectedTime: 'O(N * L)',
    expectedSpace: 'O(1)',
    estimatedTime: '20 mins',
    platform: 'LeetCode',
    platformLink: 'https://leetcode.com/problems/camelcase-matching/',
    status: 'Not Started',
    notes: '',
    bookmarked: false,
    completed: false,
    tags: ['Two Pointers', 'String', 'Trie', 'String Matching'],
    topic: 'Advanced Strings',
    companies: ['Google'],
    leetcodeNumber: 1023,
    leetcodeLink: 'https://leetcode.com/problems/camelcase-matching/',
    visualizerSlug: 'string',
    hints: ['Use two pointers to match pattern characters in query. Extra uppercase characters in query invalidate match.'],
    bruteForce: 'Regex matching per query.',
    optimalApproach: 'Two pointer subsequence check verifying capital letter constraints.',
    commonMistakes: ['Allowing extra unexpected capital letters in query.'],
    prerequisites: ['Two Pointers', 'Strings'],
    relatedQuestions: ['adv-str-20', 'adv-str-18'],
    acceptanceRate: '61.7%',
  },
  {
    id: 'adv-str-22',
    title: 'Find All Good Strings',
    category: 'advanced-strings',
    pattern: 'KMP Algorithm',
    subPattern: 'Digit DP + KMP State',
    difficulty: 'hard',
    description: 'Given size n, strings s1, s2, and evil, find number of good strings of length n that do not contain evil as substring.',
    frequency: 'high',
    starRating: 5,
    expectedTime: 'O(N * |evil|)',
    expectedSpace: 'O(N * |evil|)',
    estimatedTime: '45 mins',
    platform: 'LeetCode',
    platformLink: 'https://leetcode.com/problems/find-all-good-strings/',
    status: 'Not Started',
    notes: '',
    bookmarked: false,
    completed: false,
    tags: ['String', 'Dynamic Programming', 'KMP', 'Digit DP'],
    topic: 'Advanced Strings',
    companies: ['Google'],
    leetcodeNumber: 1397,
    leetcodeLink: 'https://leetcode.com/problems/find-all-good-strings/',
    visualizerSlug: 'string',
    hints: ['Combine Digit DP state (position, tight bound) with KMP state tracking current matching length of evil.'],
    bruteForce: 'Generate all strings between s1 and s2 and check for evil substring.',
    optimalApproach: 'Digit DP with KMP automaton transitions in O(N * |evil| * 26).',
    commonMistakes: ['Incorrect KMP fallback state transition during DP recursion.'],
    prerequisites: ['KMP Algorithm', 'Dynamic Programming'],
    relatedQuestions: ['adv-str-1', 'adv-str-4'],
    acceptanceRate: '41.3%',
  },
  {
    id: 'adv-str-23',
    title: 'Shortest Common Supersequence',
    category: 'advanced-strings',
    pattern: 'Pattern & Wildcard Matching',
    subPattern: 'LCS Backtracking Construction',
    difficulty: 'hard',
    description: 'Given two strings str1 and str2, return the shortest string that has both str1 and str2 as subsequences.',
    frequency: 'high',
    starRating: 5,
    expectedTime: 'O(N * M)',
    expectedSpace: 'O(N * M)',
    estimatedTime: '35 mins',
    platform: 'LeetCode',
    platformLink: 'https://leetcode.com/problems/shortest-common-supersequence/',
    status: 'Not Started',
    notes: '',
    bookmarked: false,
    completed: false,
    tags: ['String', 'Dynamic Programming'],
    topic: 'Advanced Strings',
    companies: ['Google', 'Amazon', 'Microsoft'],
    leetcodeNumber: 1092,
    leetcodeLink: 'https://leetcode.com/problems/shortest-common-supersequence/',
    visualizerSlug: 'string',
    hints: ['First compute Longest Common Subsequence (LCS) matrix. Backtrack from DP table adding non-LCS characters.'],
    bruteForce: 'Exponential combination of merged characters.',
    optimalApproach: 'LCS DP table followed by single-pass string construction during DP pointer walkback.',
    commonMistakes: ['Missing remaining characters when one string pointer reaches 0.'],
    prerequisites: ['LCS DP', 'Strings'],
    relatedQuestions: ['adv-str-18', 'adv-str-19'],
    acceptanceRate: '58.8%',
  },
  {
    id: 'adv-str-24',
    title: 'Polynomial Rolling Hash Key Generation',
    category: 'advanced-strings',
    pattern: 'Rabin-Karp & Rolling Hash',
    subPattern: 'Double Modulo Hashing',
    difficulty: 'medium',
    description: 'Implement a collision-resistant double-polynomial rolling hash generator for fast arbitrary range substring hashing.',
    frequency: 'medium',
    starRating: 4,
    expectedTime: 'O(N)',
    expectedSpace: 'O(N)',
    estimatedTime: '25 mins',
    platform: 'LeetCode',
    platformLink: 'https://leetcode.com/problems/polynomial-rolling-hash/',
    status: 'Not Started',
    notes: '',
    bookmarked: false,
    completed: false,
    tags: ['String', 'Rolling Hash', 'Math'],
    topic: 'Advanced Strings',
    companies: ['Google', 'Meta'],
    visualizerSlug: 'string',
    hints: ['Precompute prime powers P^k mod M1 and P^k mod M2 and inverse powers for O(1) range query.'],
    bruteForce: 'Re-hash substring from scratch O(L).',
    optimalApproach: 'Prefix hash arrays with modular inverse power lookup in O(1).',
    commonMistakes: ['Using small modulus prime leading to hash collision.'],
    prerequisites: ['Modular Arithmetic', 'Rolling Hash'],
    relatedQuestions: ['adv-str-7', 'adv-str-9'],
    acceptanceRate: '62.0%',
  },
  {
    id: 'adv-str-25',
    title: 'Suffix Tree Generalized Construction',
    category: 'advanced-strings',
    pattern: 'Suffix Structures & Automata',
    subPattern: 'Compressed Suffix Trie',
    difficulty: 'hard',
    description: 'Build a Generalized Suffix Tree for multiple strings to solve multi-pattern matching and common substring queries.',
    frequency: 'medium',
    starRating: 5,
    expectedTime: 'O(Total Length)',
    expectedSpace: 'O(Total Length)',
    estimatedTime: '50 mins',
    platform: 'LeetCode',
    platformLink: 'https://leetcode.com/problems/generalized-suffix-tree/',
    status: 'Not Started',
    notes: '',
    bookmarked: false,
    completed: false,
    tags: ['String', 'Suffix Tree', 'Graph'],
    topic: 'Advanced Strings',
    companies: ['Google'],
    visualizerSlug: 'string',
    hints: ['Append distinct terminal markers like "$1", "$2" for each string and run Ukkonen algorithm.'],
    bruteForce: 'Explicitly build uncompressed Trie of all suffixes.',
    optimalApproach: 'Ukkonen linear-time Suffix Tree algorithm with generalized terminal edges.',
    commonMistakes: ['Confusing edge label ranges when splitting internal nodes.'],
    prerequisites: ['Suffix Tree', 'Ukkonen Algorithm'],
    relatedQuestions: ['adv-str-15', 'adv-str-14'],
    acceptanceRate: '36.9%',
  },
];
