import { InterviewQuestion } from '../interviewMetadata';

export const BST_INTERVIEW_QUESTIONS: InterviewQuestion[] = [
  {
    id: 'bst-1',
    title: 'Search in a Binary Search Tree',
    category: 'bst',
    pattern: 'BST Operations',
    subPattern: 'BST Search',
    difficulty: 'easy',
    description: 'Find the node in the BST that has a value equal to val and return the subtree rooted with that node.',
    frequency: 'top',
    starRating: 5,
    expectedTime: 'O(log N)',
    expectedSpace: 'O(H)',
    estimatedTime: '15 mins',
    platform: 'LeetCode',
    platformLink: 'https://leetcode.com/problems/search-in-a-binary-search-tree/',
    status: 'Not Started',
    notes: '',
    bookmarked: false,
    completed: false,
    tags: ['Tree', 'Binary Search Tree', 'Binary Tree'],
    topic: 'Binary Search Trees',
    companies: ['Amazon', 'Google', 'Microsoft', 'Adobe'],
    leetcodeNumber: 700,
    leetcodeLink: 'https://leetcode.com/problems/search-in-a-binary-search-tree/',
    visualizerSlug: 'binary-tree-inorder',
    hints: ['Compare val with current node. Go left if val < node.val, go right if val > node.val.'],
    bruteForce: 'Perform complete binary tree traversal O(N).',
    optimalApproach: 'BST property traversal in O(H) average time.',
    commonMistakes: ['Not handling null root node.'],
    prerequisites: ['BST Basics'],
    relatedQuestions: ['bst-2', 'bst-3'],
    acceptanceRate: '78.2%',
  },
  {
    id: 'bst-2',
    title: 'Insert into a Binary Search Tree',
    category: 'bst',
    pattern: 'BST Operations',
    subPattern: 'BST Insertion',
    difficulty: 'medium',
    description: 'Insert a new value into a Binary Search Tree such that the BST property remains valid.',
    frequency: 'top',
    starRating: 5,
    expectedTime: 'O(log N)',
    expectedSpace: 'O(H)',
    estimatedTime: '20 mins',
    platform: 'LeetCode',
    platformLink: 'https://leetcode.com/problems/insert-into-a-binary-search-tree/',
    status: 'Not Started',
    notes: '',
    bookmarked: false,
    completed: false,
    tags: ['Tree', 'Binary Search Tree', 'Binary Tree'],
    topic: 'Binary Search Trees',
    companies: ['Amazon', 'Google', 'Microsoft'],
    leetcodeNumber: 701,
    leetcodeLink: 'https://leetcode.com/problems/insert-into-a-binary-search-tree/',
    visualizerSlug: 'binary-tree-inorder',
    hints: ['Walk down tree comparing node values until reaching a null spot, then attach new node.'],
    bruteForce: 'Rebuild BST array representation.',
    optimalApproach: 'Recursive or iterative insertion finding leaf location in O(H).',
    commonMistakes: ['Overwriting existing non-null child pointers.'],
    prerequisites: ['BST Operations'],
    relatedQuestions: ['bst-1', 'bst-3'],
    acceptanceRate: '74.5%',
  },
  {
    id: 'bst-3',
    title: 'Delete Node in a BST',
    category: 'bst',
    pattern: 'BST Operations',
    subPattern: 'BST Deletion',
    difficulty: 'medium',
    description: 'Delete a node with key in a BST while maintaining the Binary Search Tree property.',
    frequency: 'top',
    starRating: 5,
    expectedTime: 'O(log N)',
    expectedSpace: 'O(H)',
    estimatedTime: '30 mins',
    platform: 'LeetCode',
    platformLink: 'https://leetcode.com/problems/delete-node-in-a-bst/',
    status: 'Not Started',
    notes: '',
    bookmarked: false,
    completed: false,
    tags: ['Tree', 'Binary Search Tree', 'Binary Tree'],
    topic: 'Binary Search Trees',
    companies: ['Amazon', 'Google', 'Microsoft', 'Uber'],
    leetcodeNumber: 450,
    leetcodeLink: 'https://leetcode.com/problems/delete-node-in-a-bst/',
    visualizerSlug: 'binary-tree-inorder',
    hints: ['If node to delete has 2 children, find its inorder successor (min in right subtree), copy value, and delete successor.'],
    bruteForce: 'Extract tree values into array, remove target, rebuild tree.',
    optimalApproach: 'Inorder successor replacement in-place deletion in O(H) time.',
    commonMistakes: ['Failing to properly link parent pointer when target node has 1 child.'],
    prerequisites: ['BST Basics', 'Inorder Successor'],
    relatedQuestions: ['bst-1', 'bst-2'],
    acceptanceRate: '50.9%',
  },
  {
    id: 'bst-4',
    title: 'Validate Binary Search Tree',
    category: 'bst',
    pattern: 'BST Validation',
    subPattern: 'Range Bounds Validation',
    difficulty: 'medium',
    description: 'Determine if a given binary tree is a valid binary search tree.',
    frequency: 'top',
    starRating: 5,
    expectedTime: 'O(N)',
    expectedSpace: 'O(H)',
    estimatedTime: '25 mins',
    platform: 'LeetCode',
    platformLink: 'https://leetcode.com/problems/validate-binary-search-tree/',
    status: 'Not Started',
    notes: '',
    bookmarked: false,
    completed: false,
    tags: ['Tree', 'Depth-First Search', 'Binary Search Tree', 'Binary Tree'],
    topic: 'Binary Search Trees',
    companies: ['Amazon', 'Google', 'Microsoft', 'Meta', 'Bloomberg'],
    leetcodeNumber: 98,
    leetcodeLink: 'https://leetcode.com/problems/validate-binary-search-tree/',
    visualizerSlug: 'binary-tree-inorder',
    hints: ['Pass min and max allowable bounds recursively for each node (low < node.val < high).'],
    bruteForce: 'Check only immediate left and right child (incorrect for deep subtrees).',
    optimalApproach: 'DFS range checking (min, max) or strictly increasing Inorder traversal.',
    commonMistakes: ['Only checking node.left.val < node.val instead of enforcing bounds for full subtrees.'],
    prerequisites: ['Binary Tree Traversal'],
    relatedQuestions: ['bst-5', 'bst-22'],
    acceptanceRate: '32.4%',
  },
  {
    id: 'bst-5',
    title: 'Recover Binary Search Tree',
    category: 'bst',
    pattern: 'BST Validation',
    subPattern: 'Inorder Swapped Nodes Recovery',
    difficulty: 'hard',
    description: 'You are given the root of a binary search tree (BST), where the values of exactly two nodes were swapped by mistake. Recover the tree without changing its structure.',
    frequency: 'high',
    starRating: 5,
    expectedTime: 'O(N)',
    expectedSpace: 'O(1)',
    estimatedTime: '35 mins',
    platform: 'LeetCode',
    platformLink: 'https://leetcode.com/problems/recover-binary-search-tree/',
    status: 'Not Started',
    notes: '',
    bookmarked: false,
    completed: false,
    tags: ['Tree', 'Depth-First Search', 'Binary Search Tree', 'Binary Tree'],
    topic: 'Binary Search Trees',
    companies: ['Amazon', 'Google', 'Microsoft'],
    leetcodeNumber: 99,
    leetcodeLink: 'https://leetcode.com/problems/recover-binary-search-tree/',
    visualizerSlug: 'binary-tree-inorder',
    hints: ['During inorder traversal, find two places where prev.val > curr.val. Swap their values.'],
    bruteForce: 'Inorder traversal to array, sort array, reassign values O(N log N).',
    optimalApproach: 'Morris Inorder Traversal tracking first, second, and prev nodes in O(1) space.',
    commonMistakes: ['Not handling adjacent swapped nodes correctly.'],
    prerequisites: ['BST Inorder Traversal', 'Morris Traversal'],
    relatedQuestions: ['bst-4', 'bst-9'],
    acceptanceRate: '52.3%',
  },
  {
    id: 'bst-6',
    title: 'Lowest Common Ancestor of a BST',
    category: 'bst',
    pattern: 'LCA in BST',
    subPattern: 'BST Split Point LCA',
    difficulty: 'medium',
    description: 'Given a binary search tree (BST), find the lowest common ancestor (LCA) node of two given nodes p and q.',
    frequency: 'top',
    starRating: 5,
    expectedTime: 'O(log N)',
    expectedSpace: 'O(1)',
    estimatedTime: '20 mins',
    platform: 'LeetCode',
    platformLink: 'https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/',
    status: 'Not Started',
    notes: '',
    bookmarked: false,
    completed: false,
    tags: ['Tree', 'Depth-First Search', 'Binary Search Tree', 'Binary Tree'],
    topic: 'Binary Search Trees',
    companies: ['Amazon', 'Google', 'Microsoft', 'Meta'],
    leetcodeNumber: 235,
    leetcodeLink: 'https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/',
    visualizerSlug: 'binary-tree-inorder',
    hints: ['If both p and q are smaller than root, go left. If both are larger, go right. Otherwise, root is the LCA split point.'],
    bruteForce: 'General Binary Tree LCA algorithm using parent paths O(N).',
    optimalApproach: 'Iterative BST walk down split point in O(H) time and O(1) space.',
    commonMistakes: ['Not taking advantage of BST ordering property.'],
    prerequisites: ['BST Properties'],
    relatedQuestions: ['bst-1', 'bst-4'],
    acceptanceRate: '63.2%',
  },
  {
    id: 'bst-7',
    title: 'Kth Smallest Element in a BST',
    category: 'bst',
    pattern: 'BST Operations',
    subPattern: 'Inorder Kth Counter',
    difficulty: 'medium',
    description: 'Given the root of a binary search tree, and an integer k, return the kth smallest value (1-indexed) of all values in the tree.',
    frequency: 'top',
    starRating: 5,
    expectedTime: 'O(H + K)',
    expectedSpace: 'O(H)',
    estimatedTime: '20 mins',
    platform: 'LeetCode',
    platformLink: 'https://leetcode.com/problems/kth-smallest-element-in-a-bst/',
    status: 'Not Started',
    notes: '',
    bookmarked: false,
    completed: false,
    tags: ['Tree', 'Depth-First Search', 'Binary Search Tree', 'Binary Tree'],
    topic: 'Binary Search Trees',
    companies: ['Amazon', 'Google', 'Microsoft', 'Meta', 'Uber'],
    leetcodeNumber: 230,
    leetcodeLink: 'https://leetcode.com/problems/kth-smallest-element-in-a-bst/',
    visualizerSlug: 'binary-tree-inorder',
    hints: ['Inorder traversal of a BST visits nodes in strictly ascending sorted order. Stop at Kth visited node.'],
    bruteForce: 'Collect all nodes in array via Inorder traversal and return array[k-1].',
    optimalApproach: 'Iterative stack-based Inorder traversal early-stopping at count == k.',
    commonMistakes: ['1-based indexing vs 0-based array index confusion.'],
    prerequisites: ['BST Inorder Traversal'],
    relatedQuestions: ['bst-8', 'bst-9'],
    acceptanceRate: '71.6%',
  },
  {
    id: 'bst-8',
    title: 'Kth Largest Element in a BST',
    category: 'bst',
    pattern: 'BST Operations',
    subPattern: 'Reverse Inorder Kth Counter',
    difficulty: 'medium',
    description: 'Given the root of a Binary Search Tree and integer K, find the Kth largest element in the BST.',
    frequency: 'high',
    starRating: 4,
    expectedTime: 'O(H + K)',
    expectedSpace: 'O(H)',
    estimatedTime: '20 mins',
    platform: 'LeetCode',
    platformLink: 'https://leetcode.com/problems/kth-largest-element-in-a-bst/',
    status: 'Not Started',
    notes: '',
    bookmarked: false,
    completed: false,
    tags: ['Tree', 'Binary Search Tree'],
    topic: 'Binary Search Trees',
    companies: ['Amazon', 'Microsoft'],
    visualizerSlug: 'binary-tree-inorder',
    hints: ['Perform reverse Inorder traversal (Right -> Node -> Left) to visit nodes in descending order.'],
    bruteForce: 'Store full inorder traversal in array and pick N - K element.',
    optimalApproach: 'Reverse inorder traversal keeping counter until count == k.',
    commonMistakes: ['Traversing left child first instead of right child first.'],
    prerequisites: ['BST Traversal'],
    relatedQuestions: ['bst-7', 'bst-9'],
    acceptanceRate: '68.9%',
  },
  {
    id: 'bst-9',
    title: 'Binary Search Tree Iterator',
    category: 'bst',
    pattern: 'BST Iterator',
    subPattern: 'Controlled Inorder Traversal Stack',
    difficulty: 'medium',
    description: 'Implement the BSTIterator class that represents an iterator over the in-order traversal of a binary search tree.',
    frequency: 'top',
    starRating: 5,
    expectedTime: 'O(1) average next()',
    expectedSpace: 'O(H)',
    estimatedTime: '25 mins',
    platform: 'LeetCode',
    platformLink: 'https://leetcode.com/problems/binary-search-tree-iterator/',
    status: 'Not Started',
    notes: '',
    bookmarked: false,
    completed: false,
    tags: ['Stack', 'Tree', 'Design', 'Binary Search Tree', 'Iterator'],
    topic: 'Binary Search Trees',
    companies: ['Amazon', 'Google', 'Microsoft', 'Meta'],
    leetcodeNumber: 173,
    leetcodeLink: 'https://leetcode.com/problems/binary-search-tree-iterator/',
    visualizerSlug: 'binary-tree-inorder',
    hints: ['Maintain an explicit call stack. Push all left nodes down to leftmost leaf on initialization and next().'],
    bruteForce: 'Precompute entire inorder traversal array in constructor O(N) memory.',
    optimalApproach: 'Controlled stack pushing left children on demand giving O(H) memory and O(1) amortized next().',
    commonMistakes: ['Not pushing right subtree left-children after popping node.'],
    prerequisites: ['Inorder Traversal', 'Stack Data Structure'],
    relatedQuestions: ['bst-7', 'bst-5'],
    acceptanceRate: '70.8%',
  },
  {
    id: 'bst-10',
    title: 'Convert Sorted Array to Binary Search Tree',
    category: 'bst',
    pattern: 'Convert & Balance BST',
    subPattern: 'Divide and Conquer BST Construction',
    difficulty: 'easy',
    description: 'Given an integer array nums where elements are sorted in ascending order, convert it to a height-balanced binary search tree.',
    frequency: 'top',
    starRating: 5,
    expectedTime: 'O(N)',
    expectedSpace: 'O(log N)',
    estimatedTime: '15 mins',
    platform: 'LeetCode',
    platformLink: 'https://leetcode.com/problems/convert-sorted-array-to-binary-search-tree/',
    status: 'Not Started',
    notes: '',
    bookmarked: false,
    completed: false,
    tags: ['Array', 'Divide and Conquer', 'Tree', 'Binary Search Tree', 'Binary Tree'],
    topic: 'Binary Search Trees',
    companies: ['Amazon', 'Google', 'Microsoft', 'Meta'],
    leetcodeNumber: 108,
    leetcodeLink: 'https://leetcode.com/problems/convert-sorted-array-to-binary-search-tree/',
    visualizerSlug: 'binary-tree-inorder',
    hints: ['Middle element of array becomes root node to ensure equal node distribution on left and right subtrees.'],
    bruteForce: 'Sequentially insert elements into BST O(N^2) resulting in degenerate linked list.',
    optimalApproach: 'Recursive divide and conquer choosing mid = (left + right) / 2 as current root.',
    commonMistakes: ['Integer overflow when calculating mid index.'],
    prerequisites: ['Binary Search', 'Recursion'],
    relatedQuestions: ['bst-11', 'bst-19'],
    acceptanceRate: '71.1%',
  },
  {
    id: 'bst-11',
    title: 'Convert Sorted List to BST',
    category: 'bst',
    pattern: 'Convert & Balance BST',
    subPattern: 'Fast-Slow Pointer / Inorder Simulation',
    difficulty: 'medium',
    description: 'Given the head of a singly linked list where elements are sorted in ascending order, convert it to a height-balanced binary search tree.',
    frequency: 'high',
    starRating: 4,
    expectedTime: 'O(N)',
    expectedSpace: 'O(log N)',
    estimatedTime: '25 mins',
    platform: 'LeetCode',
    platformLink: 'https://leetcode.com/problems/convert-sorted-list-to-binary-search-tree/',
    status: 'Not Started',
    notes: '',
    bookmarked: false,
    completed: false,
    tags: ['Linked List', 'Divide and Conquer', 'Tree', 'Binary Search Tree', 'Binary Tree'],
    topic: 'Binary Search Trees',
    companies: ['Amazon', 'Google', 'Microsoft'],
    leetcodeNumber: 109,
    leetcodeLink: 'https://leetcode.com/problems/convert-sorted-list-to-binary-search-tree/',
    visualizerSlug: 'binary-tree-inorder',
    hints: ['Use slow and fast pointers to find middle linked list node or build tree bottom-up while stepping list pointer.'],
    bruteForce: 'Convert linked list to array first, then use array-to-BST approach O(N) extra space.',
    optimalApproach: 'In-order tree simulation advancing list pointer continuously in O(N) time and O(log N) space.',
    commonMistakes: ['Not disconnecting left half of linked list when finding mid node.'],
    prerequisites: ['Linked List Fast/Slow', 'BST Construction'],
    relatedQuestions: ['bst-10', 'bst-19'],
    acceptanceRate: '60.9%',
  },
  {
    id: 'bst-12',
    title: 'Trim a Binary Search Tree',
    category: 'bst',
    pattern: 'BST Operations',
    subPattern: 'Recursive Range Trimming',
    difficulty: 'medium',
    description: 'Trim the tree so that all its elements lie in [low, high]. Trimming the tree should not change the relative structure of the elements that remain.',
    frequency: 'high',
    starRating: 4,
    expectedTime: 'O(N)',
    expectedSpace: 'O(H)',
    estimatedTime: '20 mins',
    platform: 'LeetCode',
    platformLink: 'https://leetcode.com/problems/trim-a-binary-search-tree/',
    status: 'Not Started',
    notes: '',
    bookmarked: false,
    completed: false,
    tags: ['Tree', 'Depth-First Search', 'Binary Search Tree', 'Binary Tree'],
    topic: 'Binary Search Trees',
    companies: ['Amazon', 'Google'],
    leetcodeNumber: 669,
    leetcodeLink: 'https://leetcode.com/problems/trim-a-binary-search-tree/',
    visualizerSlug: 'binary-tree-inorder',
    hints: ['If node.val < low, entire left subtree is invalid, return trim(node.right). If node.val > high, return trim(node.left).'],
    bruteForce: 'Collect valid nodes in list and re-insert into new BST.',
    optimalApproach: 'Recursive subtree trim routing in O(N) time.',
    commonMistakes: ['Failing to re-assign child pointers during recursive return.'],
    prerequisites: ['BST Recursion'],
    relatedQuestions: ['bst-3', 'bst-17'],
    acceptanceRate: '66.8%',
  },
  {
    id: 'bst-13',
    title: 'Inorder Successor in BST',
    category: 'bst',
    pattern: 'BST Operations',
    subPattern: 'Successor Pointer Traversal',
    difficulty: 'medium',
    description: 'Given the root of a binary search tree and a node p in it, return the in-order successor of that node in the BST. If no in-order successor exists, return null.',
    frequency: 'top',
    starRating: 5,
    expectedTime: 'O(H)',
    expectedSpace: 'O(1)',
    estimatedTime: '20 mins',
    platform: 'LeetCode',
    platformLink: 'https://leetcode.com/problems/inorder-successor-in-bst/',
    status: 'Not Started',
    notes: '',
    bookmarked: false,
    completed: false,
    tags: ['Tree', 'Depth-First Search', 'Binary Search Tree', 'Binary Tree'],
    topic: 'Binary Search Trees',
    companies: ['Amazon', 'Google', 'Microsoft', 'Meta'],
    leetcodeNumber: 285,
    leetcodeLink: 'https://leetcode.com/problems/inorder-successor-in-bst/',
    visualizerSlug: 'binary-tree-inorder',
    hints: ['If p has right child, successor is min in right subtree. Otherwise, successor is deepest ancestor where p was in left subtree.'],
    bruteForce: 'Store complete inorder traversal array O(N) memory.',
    optimalApproach: 'Iterative BST search walk updating successor candidate whenever node.val > p.val.',
    commonMistakes: ['Not handling case where successor does not exist.'],
    prerequisites: ['BST Properties', 'Inorder Traversal'],
    relatedQuestions: ['bst-14', 'bst-9'],
    acceptanceRate: '49.1%',
  },
  {
    id: 'bst-14',
    title: 'Inorder Predecessor in BST',
    category: 'bst',
    pattern: 'BST Operations',
    subPattern: 'Predecessor Pointer Traversal',
    difficulty: 'medium',
    description: 'Given the root of a binary search tree and a node p, return the in-order predecessor of that node in the BST.',
    frequency: 'high',
    starRating: 4,
    expectedTime: 'O(H)',
    expectedSpace: 'O(1)',
    estimatedTime: '20 mins',
    platform: 'LeetCode',
    platformLink: 'https://leetcode.com/problems/inorder-predecessor-in-bst/',
    status: 'Not Started',
    notes: '',
    bookmarked: false,
    completed: false,
    tags: ['Tree', 'Binary Search Tree'],
    topic: 'Binary Search Trees',
    companies: ['Amazon', 'Microsoft'],
    visualizerSlug: 'binary-tree-inorder',
    hints: ['If p has left child, predecessor is max in left subtree. Otherwise, predecessor is deepest ancestor where p was in right subtree.'],
    bruteForce: 'Store full inorder array.',
    optimalApproach: 'Iterative BST walk updating predecessor candidate whenever node.val < p.val.',
    commonMistakes: ['Confusing predecessor with successor logic.'],
    prerequisites: ['BST Properties'],
    relatedQuestions: ['bst-13', 'bst-9'],
    acceptanceRate: '51.4%',
  },
  {
    id: 'bst-15',
    title: 'Closest Binary Search Tree Value',
    category: 'bst',
    pattern: 'Floor & Ceil in BST',
    subPattern: 'Closest Value Tracking',
    difficulty: 'easy',
    description: 'Given the root of a binary search tree and a target floating point number, find the value in the BST that is closest to target.',
    frequency: 'high',
    starRating: 4,
    expectedTime: 'O(H)',
    expectedSpace: 'O(1)',
    estimatedTime: '15 mins',
    platform: 'LeetCode',
    platformLink: 'https://leetcode.com/problems/closest-binary-search-tree-value/',
    status: 'Not Started',
    notes: '',
    bookmarked: false,
    completed: false,
    tags: ['Tree', 'Depth-First Search', 'Binary Search Tree', 'Binary Tree'],
    topic: 'Binary Search Trees',
    companies: ['Amazon', 'Google', 'Meta'],
    leetcodeNumber: 270,
    leetcodeLink: 'https://leetcode.com/problems/closest-binary-search-tree-value/',
    visualizerSlug: 'binary-tree-inorder',
    hints: ['Walk down BST updating closest value candidate. Go left if target < node.val, right if target > node.val.'],
    bruteForce: 'Scan all tree nodes O(N).',
    optimalApproach: 'Iterative BST search updating minimum absolute difference in O(H) time and O(1) space.',
    commonMistakes: ['Not updating closest value when difference is equal.'],
    prerequisites: ['BST Search'],
    relatedQuestions: ['bst-16', 'bst-26'],
    acceptanceRate: '51.8%',
  },
  {
    id: 'bst-16',
    title: 'Closest Binary Search Tree Value II',
    category: 'bst',
    pattern: 'Floor & Ceil in BST',
    subPattern: 'Double Stack K-Closest Values',
    difficulty: 'hard',
    description: 'Given the root of a binary search tree, a target value, and an integer k, return the k values in the BST that are closest to target.',
    frequency: 'high',
    starRating: 5,
    expectedTime: 'O(H + K)',
    expectedSpace: 'O(H)',
    estimatedTime: '35 mins',
    platform: 'LeetCode',
    platformLink: 'https://leetcode.com/problems/closest-binary-search-tree-value-ii/',
    status: 'Not Started',
    notes: '',
    bookmarked: false,
    completed: false,
    tags: ['Stack', 'Tree', 'Two Pointers', 'Binary Search Tree', 'Binary Tree'],
    topic: 'Binary Search Trees',
    companies: ['Google', 'Amazon'],
    leetcodeNumber: 272,
    leetcodeLink: 'https://leetcode.com/problems/closest-binary-search-tree-value-ii/',
    visualizerSlug: 'binary-tree-inorder',
    hints: ['Use two stacks for predecessor iterator and successor iterator around target value.'],
    bruteForce: 'Inorder array + sliding window or max-heap O(N log K).',
    optimalApproach: 'Dual iterator stacks (predecessor stack & successor stack) returning K closest in O(H + K).',
    commonMistakes: ['Not properly advancing predecessor / successor iterators.'],
    prerequisites: ['BST Iterator', 'Two Pointers'],
    relatedQuestions: ['bst-15', 'bst-9'],
    acceptanceRate: '56.7%',
  },
  {
    id: 'bst-17',
    title: 'Range Sum of BST',
    category: 'bst',
    pattern: 'Range & Sum Queries',
    subPattern: 'Pruned Range DFS',
    difficulty: 'easy',
    description: 'Given the root node of a binary search tree and two integers low and high, return the sum of values of all nodes with a value in the inclusive range [low, high].',
    frequency: 'top',
    starRating: 5,
    expectedTime: 'O(N)',
    expectedSpace: 'O(H)',
    estimatedTime: '15 mins',
    platform: 'LeetCode',
    platformLink: 'https://leetcode.com/problems/range-sum-of-bst/',
    status: 'Not Started',
    notes: '',
    bookmarked: false,
    completed: false,
    tags: ['Tree', 'Depth-First Search', 'Binary Search Tree', 'Binary Tree'],
    topic: 'Binary Search Trees',
    companies: ['Amazon', 'Meta', 'Google', 'Microsoft'],
    leetcodeNumber: 938,
    leetcodeLink: 'https://leetcode.com/problems/range-sum-of-bst/',
    visualizerSlug: 'binary-tree-inorder',
    hints: ['Only recurse into left subtree if node.val > low. Only recurse into right subtree if node.val < high.'],
    bruteForce: 'Visit all tree nodes and sum values in range [low, high].',
    optimalApproach: 'Pruned DFS skipping subtrees outside [low, high] range bounds.',
    commonMistakes: ['Visiting subtrees guaranteed to be out of range.'],
    prerequisites: ['BST Properties', 'Recursion'],
    relatedQuestions: ['bst-12', 'bst-28'],
    acceptanceRate: '86.1%',
  },
  {
    id: 'bst-18',
    title: 'Convert BST to Greater Tree',
    category: 'bst',
    pattern: 'Range & Sum Queries',
    subPattern: 'Reverse Inorder Accumulation',
    difficulty: 'medium',
    description: 'Convert a BST to a Greater Tree such that every key of original BST is changed to original key plus the sum of all keys greater than original key in BST.',
    frequency: 'high',
    starRating: 4,
    expectedTime: 'O(N)',
    expectedSpace: 'O(H)',
    estimatedTime: '20 mins',
    platform: 'LeetCode',
    platformLink: 'https://leetcode.com/problems/convert-bst-to-greater-tree/',
    status: 'Not Started',
    notes: '',
    bookmarked: false,
    completed: false,
    tags: ['Tree', 'Depth-First Search', 'Binary Search Tree', 'Binary Tree'],
    topic: 'Binary Search Trees',
    companies: ['Amazon', 'Google'],
    leetcodeNumber: 538,
    leetcodeLink: 'https://leetcode.com/problems/convert-bst-to-greater-tree/',
    visualizerSlug: 'binary-tree-inorder',
    hints: ['Perform reverse inorder traversal (Right -> Node -> Left) maintaining a running sum of all visited nodes.'],
    bruteForce: 'Calculate sum of greater elements for each node independently in O(N^2).',
    optimalApproach: 'Reverse inorder traversal with single running sum variable in O(N).',
    commonMistakes: ['Traversing left child first instead of right child.'],
    prerequisites: ['Reverse Inorder Traversal'],
    relatedQuestions: ['bst-8', 'bst-17'],
    acceptanceRate: '68.4%',
  },
  {
    id: 'bst-19',
    title: 'Balance a Binary Search Tree',
    category: 'bst',
    pattern: 'Convert & Balance BST',
    subPattern: 'Inorder Flattening + Mid Split',
    difficulty: 'medium',
    description: 'Given the root of a binary search tree, return a height-balanced binary search tree with the same node values.',
    frequency: 'high',
    starRating: 4,
    expectedTime: 'O(N)',
    expectedSpace: 'O(N)',
    estimatedTime: '25 mins',
    platform: 'LeetCode',
    platformLink: 'https://leetcode.com/problems/balance-a-binary-search-tree/',
    status: 'Not Started',
    notes: '',
    bookmarked: false,
    completed: false,
    tags: ['Divide and Conquer', 'Greedy', 'Tree', 'Binary Search Tree', 'Binary Tree'],
    topic: 'Binary Search Trees',
    companies: ['Amazon', 'Meta'],
    leetcodeNumber: 1382,
    leetcodeLink: 'https://leetcode.com/problems/balance-a-binary-search-tree/',
    visualizerSlug: 'binary-tree-inorder',
    hints: ['Convert BST to sorted array via inorder traversal, then construct balanced BST recursively choosing mid element as root.'],
    bruteForce: 'AVL / Red-Black tree rotations on unbalanced tree.',
    optimalApproach: 'Inorder extraction to array followed by divide and conquer mid-split tree creation in O(N).',
    commonMistakes: ['Not clearing old child pointers when rebuilding nodes.'],
    prerequisites: ['BST Inorder', 'Convert Sorted Array to BST'],
    relatedQuestions: ['bst-10', 'bst-11'],
    acceptanceRate: '80.7%',
  },
  {
    id: 'bst-20',
    title: 'All Elements in Two Binary Search Trees',
    category: 'bst',
    pattern: 'BST Operations',
    subPattern: 'Dual BST Iterator Merge',
    difficulty: 'medium',
    description: 'Given two binary search trees root1 and root2, return a list containing all the integers from both trees sorted in ascending order.',
    frequency: 'medium',
    starRating: 4,
    expectedTime: 'O(N + M)',
    expectedSpace: 'O(N + M)',
    estimatedTime: '20 mins',
    platform: 'LeetCode',
    platformLink: 'https://leetcode.com/problems/all-elements-in-two-binary-search-trees/',
    status: 'Not Started',
    notes: '',
    bookmarked: false,
    completed: false,
    tags: ['Tree', 'Depth-First Search', 'Binary Search Tree', 'Sorting', 'Binary Tree'],
    topic: 'Binary Search Trees',
    companies: ['Amazon', 'Google'],
    leetcodeNumber: 1305,
    leetcodeLink: 'https://leetcode.com/problems/all-elements-in-two-binary-search-trees/',
    visualizerSlug: 'binary-tree-inorder',
    hints: ['Perform iterative inorder traversal on both BSTs simultaneously using two stacks, merging elements like merge sort.'],
    bruteForce: 'Collect all elements into list and call Array.sort() O((N+M) log(N+M)).',
    optimalApproach: 'Two stack iterative inorder traversal merging two streams in O(N + M).',
    commonMistakes: ['Stack empty edge cases during pointer merge step.'],
    prerequisites: ['BST Iterator', 'Merge Sort'],
    relatedQuestions: ['bst-9', 'bst-10'],
    acceptanceRate: '79.6%',
  },
  {
    id: 'bst-21',
    title: 'Two Sum IV - Input is a BST',
    category: 'bst',
    pattern: 'BST Operations',
    subPattern: 'Dual Iterator Two Pointers',
    difficulty: 'easy',
    description: 'Given the root of a binary search tree and a target number k, return true if there exist two elements in the BST such that their sum is equal to k.',
    frequency: 'top',
    starRating: 5,
    expectedTime: 'O(N)',
    expectedSpace: 'O(H)',
    estimatedTime: '20 mins',
    platform: 'LeetCode',
    platformLink: 'https://leetcode.com/problems/two-sum-iv-input-is-a-bst/',
    status: 'Not Started',
    notes: '',
    bookmarked: false,
    completed: false,
    tags: ['Hash Table', 'Two Pointers', 'Tree', 'Depth-First Search', 'Breadth-First Search', 'Binary Search Tree', 'Binary Tree'],
    topic: 'Binary Search Trees',
    companies: ['Amazon', 'Google', 'Microsoft', 'Meta'],
    leetcodeNumber: 653,
    leetcodeLink: 'https://leetcode.com/problems/two-sum-iv-input-is-a-bst/',
    visualizerSlug: 'binary-tree-inorder',
    hints: ['Use HashSet while doing traversal OR use two BST iterators (normal inorder and reverse inorder) as two pointers.'],
    bruteForce: 'Collect all values in array and run Two Sum O(N) space.',
    optimalApproach: 'Forward and reverse BST iterators acting as two pointers in O(H) space.',
    commonMistakes: ['Using same node twice (e.g. node.val + node.val == k).'],
    prerequisites: ['Two Pointers', 'BST Iterator'],
    relatedQuestions: ['bst-9', 'bst-1'],
    acceptanceRate: '61.2%',
  },
  {
    id: 'bst-22',
    title: 'Check for Dead End in BST',
    category: 'bst',
    pattern: 'BST Validation',
    subPattern: 'Min-Max Range Collision',
    difficulty: 'medium',
    description: 'Given a BST with positive integer values, check whether the BST contains a dead end (a leaf node where no other node can be inserted).',
    frequency: 'high',
    starRating: 4,
    expectedTime: 'O(N)',
    expectedSpace: 'O(H)',
    estimatedTime: '20 mins',
    platform: 'LeetCode',
    platformLink: 'https://leetcode.com/problems/check-for-dead-end-in-bst/',
    status: 'Not Started',
    notes: '',
    bookmarked: false,
    completed: false,
    tags: ['Tree', 'Binary Search Tree'],
    topic: 'Binary Search Trees',
    companies: ['Amazon'],
    visualizerSlug: 'binary-tree-inorder',
    hints: ['A dead end occurs at a leaf node when min range bound + 1 == node.val == max range bound - 1.'],
    bruteForce: 'Store all node values in a HashSet, then check if leaf node X has both X-1 and X+1 in Set.',
    optimalApproach: 'DFS passing (min, max) bounds. If min == max for any leaf node, a dead end exists.',
    commonMistakes: ['Not initializing min bound to 1 (all values positive integers).'],
    prerequisites: ['BST Bounds Validation'],
    relatedQuestions: ['bst-4', 'bst-12'],
    acceptanceRate: '57.3%',
  },
  {
    id: 'bst-23',
    title: 'Largest BST Subtree',
    category: 'bst',
    pattern: 'BST Validation',
    subPattern: 'Bottom-Up Tree DP',
    difficulty: 'medium',
    description: 'Given the root of a binary tree, find the size of the largest subtree which is also a Binary Search Tree (BST).',
    frequency: 'top',
    starRating: 5,
    expectedTime: 'O(N)',
    expectedSpace: 'O(H)',
    estimatedTime: '30 mins',
    platform: 'LeetCode',
    platformLink: 'https://leetcode.com/problems/largest-bst-subtree/',
    status: 'Not Started',
    notes: '',
    bookmarked: false,
    completed: false,
    tags: ['Dynamic Programming', 'Tree', 'Depth-First Search', 'Binary Search Tree', 'Binary Tree'],
    topic: 'Binary Search Trees',
    companies: ['Amazon', 'Google', 'Microsoft'],
    leetcodeNumber: 333,
    leetcodeLink: 'https://leetcode.com/problems/largest-bst-subtree/',
    visualizerSlug: 'binary-tree-inorder',
    hints: ['Post-order DFS returning (isBST, size, min_val, max_val) from subtrees up to root.'],
    bruteForce: 'Call validateBST on every node in tree O(N^2).',
    optimalApproach: 'Bottom-up Tree DP returning (isBST, count, min, max) in O(N).',
    commonMistakes: ['Not updating overall max BST size when child is valid BST.'],
    prerequisites: ['Post-Order Traversal', 'Tree DP'],
    relatedQuestions: ['bst-4', 'bst-24'],
    acceptanceRate: '44.1%',
  },
  {
    id: 'bst-24',
    title: 'Construct BST from Preorder Traversal',
    category: 'bst',
    pattern: 'BST Operations',
    subPattern: 'Preorder Bound Construction',
    difficulty: 'medium',
    description: 'Given an array of integers preorder, which represents the preorder traversal of a BST, construct and return the root of the BST.',
    frequency: 'top',
    starRating: 5,
    expectedTime: 'O(N)',
    expectedSpace: 'O(H)',
    estimatedTime: '25 mins',
    platform: 'LeetCode',
    platformLink: 'https://leetcode.com/problems/construct-binary-search-tree-from-preorder-traversal/',
    status: 'Not Started',
    notes: '',
    bookmarked: false,
    completed: false,
    tags: ['Array', 'Stack', 'Tree', 'Binary Search Tree', 'Monotonic Stack', 'Binary Tree'],
    topic: 'Binary Search Trees',
    companies: ['Amazon', 'Google', 'Microsoft'],
    leetcodeNumber: 1008,
    leetcodeLink: 'https://leetcode.com/problems/construct-binary-search-tree-from-preorder-traversal/',
    visualizerSlug: 'binary-tree-inorder',
    hints: ['Maintain upper bound limit during recursion. If preorder[i] exceeds bound, it belongs to an upper ancestor right subtree.'],
    bruteForce: 'Insert each element one by one into BST O(N^2) or sort to get inorder and build O(N log N).',
    optimalApproach: 'Upper bound recursion passing max_val limit in O(N) linear time.',
    commonMistakes: ['Incrementing index incorrectly across recursive branches.'],
    prerequisites: ['Preorder Traversal', 'BST Invariants'],
    relatedQuestions: ['bst-2', 'bst-25'],
    acceptanceRate: '81.5%',
  },
  {
    id: 'bst-25',
    title: 'Serialize and Deserialize BST',
    category: 'bst',
    pattern: 'BST Operations',
    subPattern: 'Compact Preorder String Encoding',
    difficulty: 'medium',
    description: 'Design an algorithm to serialize a binary search tree to a string and deserialize the string back to a binary search tree.',
    frequency: 'high',
    starRating: 5,
    expectedTime: 'O(N)',
    expectedSpace: 'O(N)',
    estimatedTime: '30 mins',
    platform: 'LeetCode',
    platformLink: 'https://leetcode.com/problems/serialize-and-deserialize-bst/',
    status: 'Not Started',
    notes: '',
    bookmarked: false,
    completed: false,
    tags: ['String', 'Tree', 'Depth-First Search', 'Breadth-First Search', 'Design', 'Binary Search Tree', 'Binary Tree'],
    topic: 'Binary Search Trees',
    companies: ['Amazon', 'Google', 'Microsoft', 'Uber'],
    leetcodeNumber: 449,
    leetcodeLink: 'https://leetcode.com/problems/serialize-and-deserialize-bst/',
    visualizerSlug: 'binary-tree-inorder',
    hints: ['Serialize via Preorder traversal without null markers (BST property allows unique reconstruction with upper bounds).'],
    bruteForce: 'Include null markers like Binary Tree Serialization (takes extra space).',
    optimalApproach: 'Preorder traversal string encoding + upper bound recursive decoding in O(N).',
    commonMistakes: ['Using string delimiter parsing incorrectly.'],
    prerequisites: ['Construct BST from Preorder', 'String Manipulation'],
    relatedQuestions: ['bst-24', 'bst-1'],
    acceptanceRate: '57.8%',
  },
  {
    id: 'bst-26',
    title: 'Floor in a Binary Search Tree',
    category: 'bst',
    pattern: 'Floor & Ceil in BST',
    subPattern: 'Floor Value Search Walk',
    difficulty: 'medium',
    description: 'Given a Binary Search Tree and a key X, find the floor of X in the BST (largest value in BST <= X).',
    frequency: 'top',
    starRating: 5,
    expectedTime: 'O(H)',
    expectedSpace: 'O(1)',
    estimatedTime: '15 mins',
    platform: 'LeetCode',
    platformLink: 'https://leetcode.com/problems/floor-in-a-bst/',
    status: 'Not Started',
    notes: '',
    bookmarked: false,
    completed: false,
    tags: ['Tree', 'Binary Search Tree'],
    topic: 'Binary Search Trees',
    companies: ['Amazon', 'Microsoft', 'Adobe'],
    visualizerSlug: 'binary-tree-inorder',
    hints: ['If node.val == X, floor is X. If node.val > X, floor lies in left subtree. If node.val < X, node.val is candidate floor, move right.'],
    bruteForce: 'Inorder array scan finding max element <= X.',
    optimalApproach: 'Iterative BST search walk maintaining candidate floor variable in O(H).',
    commonMistakes: ['Returning -1 when floor candidate actually exists.'],
    prerequisites: ['BST Search'],
    relatedQuestions: ['bst-27', 'bst-15'],
    acceptanceRate: '65.2%',
  },
  {
    id: 'bst-27',
    title: 'Ceil in a Binary Search Tree',
    category: 'bst',
    pattern: 'Floor & Ceil in BST',
    subPattern: 'Ceil Value Search Walk',
    difficulty: 'medium',
    description: 'Given a Binary Search Tree and a key X, find the ceil of X in the BST (smallest value in BST >= X).',
    frequency: 'top',
    starRating: 5,
    expectedTime: 'O(H)',
    expectedSpace: 'O(1)',
    estimatedTime: '15 mins',
    platform: 'LeetCode',
    platformLink: 'https://leetcode.com/problems/ceil-in-a-bst/',
    status: 'Not Started',
    notes: '',
    bookmarked: false,
    completed: false,
    tags: ['Tree', 'Binary Search Tree'],
    topic: 'Binary Search Trees',
    companies: ['Amazon', 'Microsoft', 'Adobe'],
    visualizerSlug: 'binary-tree-inorder',
    hints: ['If node.val == X, ceil is X. If node.val < X, ceil lies in right subtree. If node.val > X, node.val is candidate ceil, move left.'],
    bruteForce: 'Inorder array scan finding min element >= X.',
    optimalApproach: 'Iterative BST search walk maintaining candidate ceil variable in O(H).',
    commonMistakes: ['Confusing ceil condition with floor condition.'],
    prerequisites: ['BST Search'],
    relatedQuestions: ['bst-26', 'bst-15'],
    acceptanceRate: '64.8%',
  },
  {
    id: 'bst-28',
    title: 'Count Nodes in Given Range in BST',
    category: 'bst',
    pattern: 'Range & Sum Queries',
    subPattern: 'Pruned Range Counter DFS',
    difficulty: 'medium',
    description: 'Given a Binary Search Tree and a range [low, high], count the number of nodes in the BST that lie in the range [low, high].',
    frequency: 'high',
    starRating: 4,
    expectedTime: 'O(N)',
    expectedSpace: 'O(H)',
    estimatedTime: '15 mins',
    platform: 'LeetCode',
    platformLink: 'https://leetcode.com/problems/count-nodes-in-given-range/',
    status: 'Not Started',
    notes: '',
    bookmarked: false,
    completed: false,
    tags: ['Tree', 'Binary Search Tree'],
    topic: 'Binary Search Trees',
    companies: ['Amazon', 'Microsoft'],
    visualizerSlug: 'binary-tree-inorder',
    hints: ['Use range pruning DFS: if node.val is inside [low, high], increment count and recurse left and right.'],
    bruteForce: 'Traverse all nodes counting matches.',
    optimalApproach: 'Pruned DFS traversal skipping out of bound branches.',
    commonMistakes: ['Not exploring both subtrees when node.val is within [low, high].'],
    prerequisites: ['BST Range Search'],
    relatedQuestions: ['bst-17', 'bst-12'],
    acceptanceRate: '72.4%',
  },
  {
    id: 'bst-29',
    title: 'Minimum Distance Between BST Nodes',
    category: 'bst',
    pattern: 'BST Operations',
    subPattern: 'Inorder Adjacent Difference',
    difficulty: 'easy',
    description: 'Given the root of a Binary Search Tree (BST), return the minimum difference between the values of any two different nodes in the tree.',
    frequency: 'high',
    starRating: 4,
    expectedTime: 'O(N)',
    expectedSpace: 'O(H)',
    estimatedTime: '15 mins',
    platform: 'LeetCode',
    platformLink: 'https://leetcode.com/problems/minimum-distance-between-bst-nodes/',
    status: 'Not Started',
    notes: '',
    bookmarked: false,
    completed: false,
    tags: ['Tree', 'Depth-First Search', 'Binary Search Tree', 'Binary Tree'],
    topic: 'Binary Search Trees',
    companies: ['Amazon', 'Google'],
    leetcodeNumber: 783,
    leetcodeLink: 'https://leetcode.com/problems/minimum-distance-between-bst-nodes/',
    visualizerSlug: 'binary-tree-inorder',
    hints: ['Inorder traversal visits nodes in sorted order. Minimum difference always occurs between adjacent elements in sorted order.'],
    bruteForce: 'Compare all pairs of nodes O(N^2).',
    optimalApproach: 'Inorder traversal tracking previous visited node value and updating min difference in O(N).',
    commonMistakes: ['Initializing min distance to 0 instead of infinity.'],
    prerequisites: ['Inorder Traversal'],
    relatedQuestions: ['bst-4', 'bst-7'],
    acceptanceRate: '59.8%',
  },
  {
    id: 'bst-30',
    title: 'Split BST',
    category: 'bst',
    pattern: 'BST Operations',
    subPattern: 'Recursive Value Splitting',
    difficulty: 'medium',
    description: 'Given the root of a BST and a target value V, split the tree into two subtrees such that one subtree has nodes <= V and the other has nodes > V.',
    frequency: 'high',
    starRating: 5,
    expectedTime: 'O(H)',
    expectedSpace: 'O(H)',
    estimatedTime: '30 mins',
    platform: 'LeetCode',
    platformLink: 'https://leetcode.com/problems/split-bst/',
    status: 'Not Started',
    notes: '',
    bookmarked: false,
    completed: false,
    tags: ['Tree', 'Depth-First Search', 'Binary Search Tree', 'Binary Tree'],
    topic: 'Binary Search Trees',
    companies: ['Amazon', 'Google'],
    leetcodeNumber: 776,
    leetcodeLink: 'https://leetcode.com/problems/split-bst/',
    visualizerSlug: 'binary-tree-inorder',
    hints: ['Recursively split. If root.val <= V, root and its left subtree belong to <= V split, recurse right on root.right.'],
    bruteForce: 'Re-insert all nodes into two new BSTs.',
    optimalApproach: 'Recursive subtree splitting returning pair of roots [<= V subtree, > V subtree] in O(H).',
    commonMistakes: ['Not correctly re-linking child branches returned from recursive split.'],
    prerequisites: ['BST Recursion'],
    relatedQuestions: ['bst-12', 'bst-3'],
    acceptanceRate: '59.1%',
  },
];
