import { InterviewQuestion } from '../interviewMetadata';

export const TRIE_INTERVIEW_QUESTIONS: InterviewQuestion[] = [
  {
    id: 'trie-1',
    title: 'Implement Trie (Prefix Tree)',
    category: 'trie',
    pattern: 'Implement Trie',
    subPattern: 'Standard Prefix Tree',
    difficulty: 'medium',
    description: 'A trie (pronounced as "try") or prefix tree is a tree data structure used to efficiently store and retrieve keys in a dataset of strings. Implement the Trie class.',
    frequency: 'top',
    starRating: 5,
    expectedTime: 'O(N)',
    expectedSpace: 'O(N * L)',
    estimatedTime: '20 mins',
    platform: 'LeetCode',
    platformLink: 'https://leetcode.com/problems/implement-trie-prefix-tree/',
    status: 'Not Started',
    notes: '',
    bookmarked: false,
    completed: false,
    tags: ['Trie', 'Design', 'String', 'Hash Table'],
    topic: 'Trie',
    companies: ['Amazon', 'Google', 'Microsoft', 'Apple', 'Meta'],
    leetcodeNumber: 208,
    leetcodeLink: 'https://leetcode.com/problems/implement-trie-prefix-tree/',
    visualizerSlug: 'trie',
    hints: ['Each TrieNode should hold an array or hash map of children nodes and a boolean isEndOfWord flag.'],
    bruteForce: 'Store strings in an array and do linear scan for matches.',
    optimalApproach: 'Use tree structure where each edge represents a character.',
    commonMistakes: ['Forgetting to set isEndOfWord to true when inserting.', 'Null pointer exception when character child does not exist.'],
    prerequisites: ['Trie', 'Trees', 'Recursion'],
    relatedQuestions: ['trie-2', 'trie-3'],
    acceptanceRate: '63.5%',
  },
  {
    id: 'trie-2',
    title: 'Design Add and Search Words Data Structure',
    category: 'trie',
    pattern: 'Word Dictionary & Search',
    subPattern: 'Wildcard Word Search',
    difficulty: 'medium',
    description: 'Design a data structure that supports adding new words and finding if a string matches any previously added string, where dots "." can match any letter.',
    frequency: 'top',
    starRating: 5,
    expectedTime: 'O(N * 26^k)',
    expectedSpace: 'O(N * L)',
    estimatedTime: '25 mins',
    platform: 'LeetCode',
    platformLink: 'https://leetcode.com/problems/design-add-and-search-words-data-structure/',
    status: 'Not Started',
    notes: '',
    bookmarked: false,
    completed: false,
    tags: ['Trie', 'Depth-First Search', 'Design', 'String'],
    topic: 'Trie',
    companies: ['Amazon', 'Facebook', 'Microsoft', 'Google'],
    leetcodeNumber: 211,
    leetcodeLink: 'https://leetcode.com/problems/design-add-and-search-words-data-structure/',
    visualizerSlug: 'trie',
    hints: ['Use recursive DFS when encountering "." to branch through all valid children.'],
    bruteForce: 'Store all words in list and use regex pattern matching.',
    optimalApproach: 'Trie with recursive DFS traversal on dot wildcard.',
    commonMistakes: ['Not exploring all 26 child branches when encountering a dot.'],
    prerequisites: ['Trie', 'DFS'],
    relatedQuestions: ['trie-1', 'trie-7'],
    acceptanceRate: '45.2%',
  },
  {
    id: 'trie-3',
    title: 'Search Suggestions System',
    category: 'trie',
    pattern: 'Prefix Searching',
    subPattern: 'Autocomplete Suggestions',
    difficulty: 'medium',
    description: 'Design a system that outputs up to three lexicographically minimum words matching the prefix after each character of search word is typed.',
    frequency: 'top',
    starRating: 5,
    expectedTime: 'O(N * L + M)',
    expectedSpace: 'O(N * L)',
    estimatedTime: '25 mins',
    platform: 'LeetCode',
    platformLink: 'https://leetcode.com/problems/search-suggestions-system/',
    status: 'Not Started',
    notes: '',
    bookmarked: false,
    completed: false,
    tags: ['Trie', 'String', 'Binary Search', 'Sorting'],
    topic: 'Trie',
    companies: ['Amazon', 'Google', 'Apple', 'Microsoft'],
    leetcodeNumber: 1268,
    leetcodeLink: 'https://leetcode.com/problems/search-suggestions-system/',
    visualizerSlug: 'trie',
    hints: ['Store top 3 suggestions at each TrieNode during insertion or use DFS on Trie.'],
    bruteForce: 'Filter and sort entire product list for every character typed.',
    optimalApproach: 'Pre-sort products and insert into Trie caching top 3 words per node.',
    commonMistakes: ['Not sorting words beforehand to get lexicographical order easily.'],
    prerequisites: ['Trie', 'Sorting'],
    relatedQuestions: ['trie-1', 'trie-4'],
    acceptanceRate: '65.8%',
  },
  {
    id: 'trie-4',
    title: 'Replace Words',
    category: 'trie',
    pattern: 'Prefix Searching',
    subPattern: 'Root Word Replacement',
    difficulty: 'medium',
    description: 'Given a dictionary consisting of roots and a sentence, replace all derivatives in the sentence with the root having the shortest length.',
    frequency: 'high',
    starRating: 4,
    expectedTime: 'O(N * L)',
    expectedSpace: 'O(R * L)',
    estimatedTime: '20 mins',
    platform: 'LeetCode',
    platformLink: 'https://leetcode.com/problems/replace-words/',
    status: 'Not Started',
    notes: '',
    bookmarked: false,
    completed: false,
    tags: ['Trie', 'Array', 'Hash Table', 'String'],
    topic: 'Trie',
    companies: ['Uber', 'Amazon', 'Google'],
    leetcodeNumber: 648,
    leetcodeLink: 'https://leetcode.com/problems/replace-words/',
    visualizerSlug: 'trie',
    hints: ['Build a Trie with all roots, then for each word, traverse Trie to find the shortest matching root prefix.'],
    bruteForce: 'Check each word against all roots in dictionary.',
    optimalApproach: 'Insert dictionary into Trie, find shortest prefix match per word in O(L).',
    commonMistakes: ['Not stopping at the first isEndOfWord flag (shortest root required).'],
    prerequisites: ['Trie', 'Strings'],
    relatedQuestions: ['trie-1', 'trie-10'],
    acceptanceRate: '63.1%',
  },
  {
    id: 'trie-5',
    title: 'Maximum XOR of Two Numbers in an Array',
    category: 'trie',
    pattern: 'Maximum XOR Queries',
    subPattern: 'Bitwise Binary Trie',
    difficulty: 'medium',
    description: 'Given an integer array nums, return the maximum result of nums[i] XOR nums[j], where 0 <= i <= j < n.',
    frequency: 'top',
    starRating: 5,
    expectedTime: 'O(N * 32)',
    expectedSpace: 'O(N * 32)',
    estimatedTime: '30 mins',
    platform: 'LeetCode',
    platformLink: 'https://leetcode.com/problems/maximum-xor-of-two-numbers-in-an-array/',
    status: 'Not Started',
    notes: '',
    bookmarked: false,
    completed: false,
    tags: ['Trie', 'Array', 'Bit Manipulation'],
    topic: 'Trie',
    companies: ['Google', 'Amazon', 'Microsoft', 'Meta'],
    leetcodeNumber: 421,
    leetcodeLink: 'https://leetcode.com/problems/maximum-xor-of-two-numbers-in-an-array/',
    visualizerSlug: 'trie',
    hints: ['Represent numbers as 32-bit binary strings and insert into a Binary Trie. For max XOR, greedily select opposite bit at each step.'],
    bruteForce: 'Check all pairs in O(N^2) time.',
    optimalApproach: 'Binary Trie insertion followed by opposite-bit greedy path search in O(32 * N).',
    commonMistakes: ['Not checking from most significant bit (bit 31 down to bit 0).'],
    prerequisites: ['Trie', 'Bit Manipulation'],
    relatedQuestions: ['trie-6', 'trie-18'],
    acceptanceRate: '54.2%',
  },
  {
    id: 'trie-6',
    title: 'Maximum XOR With an Element From Array',
    category: 'trie',
    pattern: 'Maximum XOR Queries',
    subPattern: 'Offline Queries with Binary Trie',
    difficulty: 'hard',
    description: 'Answer multiple queries of the form (x, m) finding max (x XOR nums[j]) such that nums[j] <= m.',
    frequency: 'high',
    starRating: 5,
    expectedTime: 'O((N + Q) log N)',
    expectedSpace: 'O(N * 32)',
    estimatedTime: '40 mins',
    platform: 'LeetCode',
    platformLink: 'https://leetcode.com/problems/maximum-xor-with-an-element-from-array/',
    status: 'Not Started',
    notes: '',
    bookmarked: false,
    completed: false,
    tags: ['Trie', 'Array', 'Bit Manipulation', 'Sorting'],
    topic: 'Trie',
    companies: ['Google', 'Amazon'],
    leetcodeNumber: 1707,
    leetcodeLink: 'https://leetcode.com/problems/maximum-xor-with-an-element-from-array/',
    visualizerSlug: 'trie',
    hints: ['Sort both nums and queries by upper bound m. Insert nums into Binary Trie offline as m increases.'],
    bruteForce: 'Filter array per query and find maximum XOR in O(N * Q).',
    optimalApproach: 'Offline query processing with sorted array and dynamic Trie insertion.',
    commonMistakes: ['Forgetting to preserve original query order in final answer array.'],
    prerequisites: ['Trie', 'Bitwise XOR', 'Offline Queries'],
    relatedQuestions: ['trie-5', 'trie-18'],
    acceptanceRate: '48.9%',
  },
  {
    id: 'trie-7',
    title: 'Word Search II (Trie + DFS)',
    category: 'trie',
    pattern: 'Advanced Trie Applications',
    subPattern: 'Grid Backtracking + Trie',
    difficulty: 'hard',
    description: 'Given an m x n board of characters and a list of strings words, return all words on the board found by adjacent cell movements.',
    frequency: 'top',
    starRating: 5,
    expectedTime: 'O(M * N * 4^L)',
    expectedSpace: 'O(W * L)',
    estimatedTime: '45 mins',
    platform: 'LeetCode',
    platformLink: 'https://leetcode.com/problems/word-search-ii/',
    status: 'Not Started',
    notes: '',
    bookmarked: false,
    completed: false,
    tags: ['Trie', 'Array', 'Backtracking', 'Matrix'],
    topic: 'Trie',
    companies: ['Amazon', 'Microsoft', 'Uber', 'Google', 'Apple'],
    leetcodeNumber: 212,
    leetcodeLink: 'https://leetcode.com/problems/word-search-ii/',
    visualizerSlug: 'trie',
    hints: ['Store words in Trie. Prune DFS grid traversal immediately if current path is not a prefix in Trie.'],
    bruteForce: 'Run Word Search I for each word individually.',
    optimalApproach: 'Build Trie of all words, traverse grid with DFS while stepping down Trie nodes.',
    commonMistakes: ['Not pruning visited words or Trie nodes, causing TLE on repeated words.'],
    prerequisites: ['Trie', 'Backtracking', 'Grid DFS'],
    relatedQuestions: ['trie-2', 'trie-1'],
    acceptanceRate: '36.4%',
  },
  {
    id: 'trie-8',
    title: 'Sum of Prefix Scores of Strings',
    category: 'trie',
    pattern: 'Prefix Searching',
    subPattern: 'Node Counter Trie',
    difficulty: 'hard',
    description: 'Compute the total score of each string in words, where score is the sum of scores of all non-empty prefixes of that string.',
    frequency: 'high',
    starRating: 4,
    expectedTime: 'O(N * L)',
    expectedSpace: 'O(N * L)',
    estimatedTime: '30 mins',
    platform: 'LeetCode',
    platformLink: 'https://leetcode.com/problems/sum-of-prefix-scores-of-strings/',
    status: 'Not Started',
    notes: '',
    bookmarked: false,
    completed: false,
    tags: ['Trie', 'Array', 'String', 'Counting'],
    topic: 'Trie',
    companies: ['Google', 'Amazon'],
    leetcodeNumber: 2416,
    leetcodeLink: 'https://leetcode.com/problems/sum-of-prefix-scores-of-strings/',
    visualizerSlug: 'trie',
    hints: ['Store a passCount integer at each TrieNode incremented during insertion.'],
    bruteForce: 'Count prefix matches pair by pair in O(N^2 * L).',
    optimalApproach: 'Insert all words into Trie maintaining visit counts on nodes, then query each word in O(L).',
    commonMistakes: ['Overcounting by re-traversing or not maintaining count during insertion.'],
    prerequisites: ['Trie', 'Prefix Trees'],
    relatedQuestions: ['trie-1', 'trie-10'],
    acceptanceRate: '52.1%',
  },
  {
    id: 'trie-9',
    title: 'Longest Word in Dictionary',
    category: 'trie',
    pattern: 'Prefix Searching',
    subPattern: 'Complete Prefix Word',
    difficulty: 'medium',
    description: 'Find the longest word in words that can be built one character at a time by other words in words.',
    frequency: 'medium',
    starRating: 4,
    expectedTime: 'O(N * L)',
    expectedSpace: 'O(N * L)',
    estimatedTime: '25 mins',
    platform: 'LeetCode',
    platformLink: 'https://leetcode.com/problems/longest-word-in-dictionary/',
    status: 'Not Started',
    notes: '',
    bookmarked: false,
    completed: false,
    tags: ['Trie', 'Array', 'Hash Table', 'String', 'BFS'],
    topic: 'Trie',
    companies: ['Amazon', 'Google'],
    leetcodeNumber: 720,
    leetcodeLink: 'https://leetcode.com/problems/longest-word-in-dictionary/',
    visualizerSlug: 'trie',
    hints: ['Insert all words into Trie, then run BFS/DFS ensuring every step passes through valid word nodes.'],
    bruteForce: 'Check all prefixes of each word using a hash set.',
    optimalApproach: 'Trie insertion + BFS from root tracking valid word node continuations.',
    commonMistakes: ['Not returning lexicographically smallest word in case of length tie.'],
    prerequisites: ['Trie', 'BFS'],
    relatedQuestions: ['trie-1', 'trie-3'],
    acceptanceRate: '52.7%',
  },
  {
    id: 'trie-10',
    title: 'Count Prefixes of a Given String',
    category: 'trie',
    pattern: 'Prefix Searching',
    subPattern: 'Simple Prefix Check',
    difficulty: 'easy',
    description: 'Given an array of strings words and a string s, return the number of strings in words that are a prefix of s.',
    frequency: 'medium',
    starRating: 3,
    expectedTime: 'O(N * L)',
    expectedSpace: 'O(1)',
    estimatedTime: '10 mins',
    platform: 'LeetCode',
    platformLink: 'https://leetcode.com/problems/count-prefixes-of-a-given-string/',
    status: 'Not Started',
    notes: '',
    bookmarked: false,
    completed: false,
    tags: ['Trie', 'Array', 'String'],
    topic: 'Trie',
    companies: ['Amazon', 'Microsoft'],
    leetcodeNumber: 2255,
    leetcodeLink: 'https://leetcode.com/problems/count-prefixes-of-a-given-string/',
    visualizerSlug: 'trie',
    hints: ['Check if s.startsWith(w) for each word, or use Trie for multiple search strings.'],
    bruteForce: 'Compare each word prefix with s.',
    optimalApproach: 'Direct prefix match or Trie traversal.',
    commonMistakes: ['Confusing string prefix with substring.'],
    prerequisites: ['String Manipulation'],
    relatedQuestions: ['trie-4', 'trie-8'],
    acceptanceRate: '73.4%',
  },
  {
    id: 'trie-11',
    title: 'Map Sum Pairs',
    category: 'trie',
    pattern: 'Prefix Searching',
    subPattern: 'Prefix Value Summation',
    difficulty: 'medium',
    description: 'Design a MapSum class supporting insert(key, val) and sum(prefix) returning total values of all keys starting with prefix.',
    frequency: 'medium',
    starRating: 4,
    expectedTime: 'O(L)',
    expectedSpace: 'O(N * L)',
    estimatedTime: '20 mins',
    platform: 'LeetCode',
    platformLink: 'https://leetcode.com/problems/map-sum-pairs/',
    status: 'Not Started',
    notes: '',
    bookmarked: false,
    completed: false,
    tags: ['Trie', 'Hash Table', 'String', 'Design'],
    topic: 'Trie',
    companies: ['Amazon', 'Google'],
    leetcodeNumber: 677,
    leetcodeLink: 'https://leetcode.com/problems/map-sum-pairs/',
    visualizerSlug: 'trie',
    hints: ['Maintain prefix sums directly at Trie nodes or perform DFS from matching prefix node.'],
    bruteForce: 'Iterate over all stored key-value pairs and filter by prefix.',
    optimalApproach: 'Trie with cached prefix sum at each node updated on insert.',
    commonMistakes: ['Not handling key overwriting correctly when updating existing key value.'],
    prerequisites: ['Trie', 'Hash Map'],
    relatedQuestions: ['trie-1', 'trie-8'],
    acceptanceRate: '56.9%',
  },
  {
    id: 'trie-12',
    title: 'Stream of Characters',
    category: 'trie',
    pattern: 'Advanced Trie Applications',
    subPattern: 'Reversed Trie Streaming',
    difficulty: 'hard',
    description: 'Design an algorithm that accepts a stream of characters and checks if any suffix of parsed characters matches a word in dictionary.',
    frequency: 'high',
    starRating: 5,
    expectedTime: 'O(L)',
    expectedSpace: 'O(N * L)',
    estimatedTime: '35 mins',
    platform: 'LeetCode',
    platformLink: 'https://leetcode.com/problems/stream-of-characters/',
    status: 'Not Started',
    notes: '',
    bookmarked: false,
    completed: false,
    tags: ['Trie', 'Array', 'String', 'Design', 'Data Stream'],
    topic: 'Trie',
    companies: ['Google', 'Amazon', 'Meta'],
    leetcodeNumber: 1032,
    leetcodeLink: 'https://leetcode.com/problems/stream-of-characters/',
    visualizerSlug: 'trie',
    hints: ['Insert words in REVERSE order into Trie. On each stream query, search backwards from newest character.'],
    bruteForce: 'Store history buffer and test all words against stream suffix.',
    optimalApproach: 'Reversed Trie search matching recent character stream suffix in O(Max Word Length).',
    commonMistakes: ['Searching forwards instead of backwards in stream history.'],
    prerequisites: ['Trie', 'Streaming Algorithm'],
    relatedQuestions: ['trie-1', 'trie-7'],
    acceptanceRate: '51.3%',
  },
  {
    id: 'trie-13',
    title: 'Longest Common Prefix using Trie',
    category: 'trie',
    pattern: 'Prefix Searching',
    subPattern: 'Single Child Traversal',
    difficulty: 'easy',
    description: 'Find the longest common prefix among an array of strings using a Trie data structure.',
    frequency: 'medium',
    starRating: 3,
    expectedTime: 'O(N * L)',
    expectedSpace: 'O(N * L)',
    estimatedTime: '15 mins',
    platform: 'LeetCode',
    platformLink: 'https://leetcode.com/problems/longest-common-prefix/',
    status: 'Not Started',
    notes: '',
    bookmarked: false,
    completed: false,
    tags: ['Trie', 'String'],
    topic: 'Trie',
    companies: ['Amazon', 'Google', 'Microsoft'],
    leetcodeNumber: 14,
    leetcodeLink: 'https://leetcode.com/problems/longest-common-prefix/',
    visualizerSlug: 'trie',
    hints: ['Insert all strings into Trie, then traverse down from root as long as there is exactly one child and no end-of-word.'],
    bruteForce: 'Character by character vertical scanning across strings.',
    optimalApproach: 'Trie branch walk until child count > 1 or isEndOfWord is true.',
    commonMistakes: ['Continuing past an isEndOfWord flag for a shorter word.'],
    prerequisites: ['Trie Basics'],
    relatedQuestions: ['trie-1', 'trie-10'],
    acceptanceRate: '41.8%',
  },
  {
    id: 'trie-14',
    title: 'Palindrome Pairs',
    category: 'trie',
    pattern: 'Advanced Trie Applications',
    subPattern: 'Trie Palindrome Prefix Match',
    difficulty: 'hard',
    description: 'Given a list of unique words, find all pairs of distinct indices (i, j) such that the concatenation of words[i] + words[j] is a palindrome.',
    frequency: 'top',
    starRating: 5,
    expectedTime: 'O(N * L^2)',
    expectedSpace: 'O(N * L)',
    estimatedTime: '45 mins',
    platform: 'LeetCode',
    platformLink: 'https://leetcode.com/problems/palindrome-pairs/',
    status: 'Not Started',
    notes: '',
    bookmarked: false,
    completed: false,
    tags: ['Trie', 'Array', 'Hash Table', 'String'],
    topic: 'Trie',
    companies: ['Airbnb', 'Google', 'Amazon'],
    leetcodeNumber: 336,
    leetcodeLink: 'https://leetcode.com/problems/palindrome-pairs/',
    visualizerSlug: 'trie',
    hints: ['Insert reversed words into Trie while storing palindrome suffix list at nodes.'],
    bruteForce: 'Check all N^2 concatenated pairs for palindrome condition.',
    optimalApproach: 'Reversed Trie insertion combined with prefix/suffix palindrome checks in O(N * L^2).',
    commonMistakes: ['Handling empty string edge cases and self-pair duplicates.'],
    prerequisites: ['Trie', 'Palindrome Checking'],
    relatedQuestions: ['trie-12', 'trie-7'],
    acceptanceRate: '35.2%',
  },
  {
    id: 'trie-15',
    title: 'Shortest Unique Prefix for Every Word',
    category: 'trie',
    pattern: 'Prefix Searching',
    subPattern: 'Unique Path Detection',
    difficulty: 'medium',
    description: 'Given an array of words, find the shortest unique prefix for each word in the array.',
    frequency: 'high',
    starRating: 4,
    expectedTime: 'O(N * L)',
    expectedSpace: 'O(N * L)',
    estimatedTime: '25 mins',
    platform: 'LeetCode',
    platformLink: 'https://leetcode.com/problems/shortest-unique-prefix/',
    status: 'Not Started',
    notes: '',
    bookmarked: false,
    completed: false,
    tags: ['Trie', 'String'],
    topic: 'Trie',
    companies: ['Google', 'Microsoft'],
    visualizerSlug: 'trie',
    hints: ['Maintain frequency count of visits at each Trie node during insertion. Stop prefix search when visit count equals 1.'],
    bruteForce: 'Compare every prefix of each word against all other words.',
    optimalApproach: 'Build Trie tracking frequency at each node, then query path until node frequency is 1.',
    commonMistakes: ['Not handling case where one word is a prefix of another.'],
    prerequisites: ['Trie'],
    relatedQuestions: ['trie-1', 'trie-8'],
    acceptanceRate: '58.4%',
  },
  {
    id: 'trie-16',
    title: 'Index Pairs of a String',
    category: 'trie',
    pattern: 'Prefix Searching',
    subPattern: 'Multi-pattern Search',
    difficulty: 'easy',
    description: 'Given a text string and a list of words, return all index pairs [i, j] such that substring text[i...j] is in words.',
    frequency: 'medium',
    starRating: 3,
    expectedTime: 'O(N^2 + W * L)',
    expectedSpace: 'O(W * L)',
    estimatedTime: '20 mins',
    platform: 'LeetCode',
    platformLink: 'https://leetcode.com/problems/index-pairs-of-a-string/',
    status: 'Not Started',
    notes: '',
    bookmarked: false,
    completed: false,
    tags: ['Trie', 'String', 'Sorting'],
    topic: 'Trie',
    companies: ['Amazon'],
    leetcodeNumber: 1065,
    leetcodeLink: 'https://leetcode.com/problems/index-pairs-of-a-string/',
    visualizerSlug: 'trie',
    hints: ['Insert words into Trie. For each starting index in text, walk down Trie recording matched end indices.'],
    bruteForce: 'Check substrings starting at each position using set lookup.',
    optimalApproach: 'Trie multi-pattern traversal starting at every position i in text.',
    commonMistakes: ['Missing duplicate range matches.'],
    prerequisites: ['Trie', 'String Search'],
    relatedQuestions: ['trie-1', 'trie-4'],
    acceptanceRate: '67.3%',
  },
  {
    id: 'trie-17',
    title: 'Design File System using Trie',
    category: 'trie',
    pattern: 'Implement Trie',
    subPattern: 'Hierarchical Path Trie',
    difficulty: 'medium',
    description: 'Design a file system that allows creating new paths and associating them with integer values using tree hierarchy.',
    frequency: 'high',
    starRating: 4,
    expectedTime: 'O(L)',
    expectedSpace: 'O(N * L)',
    estimatedTime: '25 mins',
    platform: 'LeetCode',
    platformLink: 'https://leetcode.com/problems/design-file-system/',
    status: 'Not Started',
    notes: '',
    bookmarked: false,
    completed: false,
    tags: ['Trie', 'Hash Table', 'String', 'Design'],
    topic: 'Trie',
    companies: ['Google', 'Amazon', 'Microsoft'],
    leetcodeNumber: 1166,
    leetcodeLink: 'https://leetcode.com/problems/design-file-system/',
    visualizerSlug: 'trie',
    hints: ['Split path components by "/" and represent folder components as child nodes in Trie.'],
    bruteForce: 'Use hash map with full path string checking parent existence.',
    optimalApproach: 'Hierarchical Trie structure where nodes represent directory names.',
    commonMistakes: ['Failing to verify parent path exists before creating child path.'],
    prerequisites: ['Trie', 'Design'],
    relatedQuestions: ['trie-1', 'trie-11'],
    acceptanceRate: '61.2%',
  },
  {
    id: 'trie-18',
    title: 'Maximum Genetic Difference Query',
    category: 'trie',
    pattern: 'Maximum XOR Queries',
    subPattern: 'Tree Path XOR Trie',
    difficulty: 'hard',
    description: 'Find max (val XOR node_val) for queries (node, val) on a rooted tree hierarchy.',
    frequency: 'high',
    starRating: 5,
    expectedTime: 'O((N + Q) * 18)',
    expectedSpace: 'O(N * 18)',
    estimatedTime: '45 mins',
    platform: 'LeetCode',
    platformLink: 'https://leetcode.com/problems/maximum-genetic-difference-query/',
    status: 'Not Started',
    notes: '',
    bookmarked: false,
    completed: false,
    tags: ['Trie', 'Array', 'Bit Manipulation', 'Tree', 'DFS'],
    topic: 'Trie',
    companies: ['Google'],
    leetcodeNumber: 1938,
    leetcodeLink: 'https://leetcode.com/problems/maximum-genetic-difference-query/',
    visualizerSlug: 'trie',
    hints: ['DFS on tree while dynamically inserting/deleting current node value in Binary Trie.'],
    bruteForce: 'Traverse root to node path for every query in O(Q * N).',
    optimalApproach: 'Trie with backtracking state during DFS traversal over tree structure.',
    commonMistakes: ['Forgetting to decrement Trie count / backtrack on recursive return.'],
    prerequisites: ['Trie', 'Tree DFS', 'Bitwise XOR'],
    relatedQuestions: ['trie-5', 'trie-6'],
    acceptanceRate: '41.6%',
  },
];
